// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiahwinfo.proto;

public interface AudioPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.AudioPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 timestamp = 1;</code>
   * @return The timestamp.
   */
  int getTimestamp();

  /**
   * <code>repeated bytes data = 2;</code>
   * @return A list containing the data.
   */
  java.util.List<com.google.protobuf.ByteString> getDataList();
  /**
   * <code>repeated bytes data = 2;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated bytes data = 2;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  com.google.protobuf.ByteString getData(int index);

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioEncoding encoding = 3;</code>
   * @return The enum numeric value on the wire for encoding.
   */
  int getEncodingValue();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioEncoding encoding = 3;</code>
   * @return The encoding.
   */
  info.malenkov.aspiahwinfo.proto.AudioEncoding getEncoding();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioPacket.SamplingRate sampling_rate = 4;</code>
   * @return The enum numeric value on the wire for samplingRate.
   */
  int getSamplingRateValue();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioPacket.SamplingRate sampling_rate = 4;</code>
   * @return The samplingRate.
   */
  info.malenkov.aspiahwinfo.proto.AudioPacket.SamplingRate getSamplingRate();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioPacket.BytesPerSample bytes_per_sample = 5;</code>
   * @return The enum numeric value on the wire for bytesPerSample.
   */
  int getBytesPerSampleValue();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioPacket.BytesPerSample bytes_per_sample = 5;</code>
   * @return The bytesPerSample.
   */
  info.malenkov.aspiahwinfo.proto.AudioPacket.BytesPerSample getBytesPerSample();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioPacket.Channels channels = 6;</code>
   * @return The enum numeric value on the wire for channels.
   */
  int getChannelsValue();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.AudioPacket.Channels channels = 6;</code>
   * @return The channels.
   */
  info.malenkov.aspiahwinfo.proto.AudioPacket.Channels getChannels();
}
