// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

/**
 * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Connections}
 */
public final class Connections extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.Connections)
    ConnectionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Connections.newBuilder() to construct.
  private Connections(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Connections() {
    connection_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Connections();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Connections(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              connection_ = new java.util.ArrayList<info.malenkov.aspiahwinfo.proto.Connections.Connection>();
              mutable_bitField0_ |= 0x00000001;
            }
            connection_.add(
                input.readMessage(info.malenkov.aspiahwinfo.proto.Connections.Connection.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        connection_ = java.util.Collections.unmodifiableList(connection_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiahwinfo.proto.Connections.class, info.malenkov.aspiahwinfo.proto.Connections.Builder.class);
  }

  public interface ConnectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.Connections.Connection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string process_name = 1;</code>
     * @return The processName.
     */
    java.lang.String getProcessName();
    /**
     * <code>string process_name = 1;</code>
     * @return The bytes for processName.
     */
    com.google.protobuf.ByteString
        getProcessNameBytes();

    /**
     * <code>string protocol = 2;</code>
     * @return The protocol.
     */
    java.lang.String getProtocol();
    /**
     * <code>string protocol = 2;</code>
     * @return The bytes for protocol.
     */
    com.google.protobuf.ByteString
        getProtocolBytes();

    /**
     * <code>string local_address = 3;</code>
     * @return The localAddress.
     */
    java.lang.String getLocalAddress();
    /**
     * <code>string local_address = 3;</code>
     * @return The bytes for localAddress.
     */
    com.google.protobuf.ByteString
        getLocalAddressBytes();

    /**
     * <code>string remote_address = 4;</code>
     * @return The remoteAddress.
     */
    java.lang.String getRemoteAddress();
    /**
     * <code>string remote_address = 4;</code>
     * @return The bytes for remoteAddress.
     */
    com.google.protobuf.ByteString
        getRemoteAddressBytes();

    /**
     * <code>uint32 local_port = 5;</code>
     * @return The localPort.
     */
    int getLocalPort();

    /**
     * <code>uint32 remote_port = 6;</code>
     * @return The remotePort.
     */
    int getRemotePort();

    /**
     * <code>string state = 7;</code>
     * @return The state.
     */
    java.lang.String getState();
    /**
     * <code>string state = 7;</code>
     * @return The bytes for state.
     */
    com.google.protobuf.ByteString
        getStateBytes();
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Connections.Connection}
   */
  public static final class Connection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.Connections.Connection)
      ConnectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Connection.newBuilder() to construct.
    private Connection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Connection() {
      processName_ = "";
      protocol_ = "";
      localAddress_ = "";
      remoteAddress_ = "";
      state_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Connection();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Connection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              processName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              protocol_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              localAddress_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              remoteAddress_ = s;
              break;
            }
            case 40: {

              localPort_ = input.readUInt32();
              break;
            }
            case 48: {

              remotePort_ = input.readUInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.Connections.Connection.class, info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder.class);
    }

    public static final int PROCESS_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object processName_;
    /**
     * <code>string process_name = 1;</code>
     * @return The processName.
     */
    @java.lang.Override
    public java.lang.String getProcessName() {
      java.lang.Object ref = processName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processName_ = s;
        return s;
      }
    }
    /**
     * <code>string process_name = 1;</code>
     * @return The bytes for processName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProcessNameBytes() {
      java.lang.Object ref = processName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOCOL_FIELD_NUMBER = 2;
    private volatile java.lang.Object protocol_;
    /**
     * <code>string protocol = 2;</code>
     * @return The protocol.
     */
    @java.lang.Override
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      }
    }
    /**
     * <code>string protocol = 2;</code>
     * @return The bytes for protocol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCAL_ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object localAddress_;
    /**
     * <code>string local_address = 3;</code>
     * @return The localAddress.
     */
    @java.lang.Override
    public java.lang.String getLocalAddress() {
      java.lang.Object ref = localAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string local_address = 3;</code>
     * @return The bytes for localAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocalAddressBytes() {
      java.lang.Object ref = localAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMOTE_ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object remoteAddress_;
    /**
     * <code>string remote_address = 4;</code>
     * @return The remoteAddress.
     */
    @java.lang.Override
    public java.lang.String getRemoteAddress() {
      java.lang.Object ref = remoteAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remoteAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string remote_address = 4;</code>
     * @return The bytes for remoteAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemoteAddressBytes() {
      java.lang.Object ref = remoteAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remoteAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCAL_PORT_FIELD_NUMBER = 5;
    private int localPort_;
    /**
     * <code>uint32 local_port = 5;</code>
     * @return The localPort.
     */
    @java.lang.Override
    public int getLocalPort() {
      return localPort_;
    }

    public static final int REMOTE_PORT_FIELD_NUMBER = 6;
    private int remotePort_;
    /**
     * <code>uint32 remote_port = 6;</code>
     * @return The remotePort.
     */
    @java.lang.Override
    public int getRemotePort() {
      return remotePort_;
    }

    public static final int STATE_FIELD_NUMBER = 7;
    private volatile java.lang.Object state_;
    /**
     * <code>string state = 7;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string state = 7;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, processName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protocol_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, protocol_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, localAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(remoteAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, remoteAddress_);
      }
      if (localPort_ != 0) {
        output.writeUInt32(5, localPort_);
      }
      if (remotePort_ != 0) {
        output.writeUInt32(6, remotePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, processName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protocol_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, protocol_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, localAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(remoteAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, remoteAddress_);
      }
      if (localPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, localPort_);
      }
      if (remotePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, remotePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof info.malenkov.aspiahwinfo.proto.Connections.Connection)) {
        return super.equals(obj);
      }
      info.malenkov.aspiahwinfo.proto.Connections.Connection other = (info.malenkov.aspiahwinfo.proto.Connections.Connection) obj;

      if (!getProcessName()
          .equals(other.getProcessName())) return false;
      if (!getProtocol()
          .equals(other.getProtocol())) return false;
      if (!getLocalAddress()
          .equals(other.getLocalAddress())) return false;
      if (!getRemoteAddress()
          .equals(other.getRemoteAddress())) return false;
      if (getLocalPort()
          != other.getLocalPort()) return false;
      if (getRemotePort()
          != other.getRemotePort()) return false;
      if (!getState()
          .equals(other.getState())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROCESS_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getProcessName().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocol().hashCode();
      hash = (37 * hash) + LOCAL_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getLocalAddress().hashCode();
      hash = (37 * hash) + REMOTE_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteAddress().hashCode();
      hash = (37 * hash) + LOCAL_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getLocalPort();
      hash = (37 * hash) + REMOTE_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getRemotePort();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.Connections.Connection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.Connections.Connection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Connections.Connection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.Connections.Connection)
        info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.malenkov.aspiahwinfo.proto.Connections.Connection.class, info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder.class);
      }

      // Construct using info.malenkov.aspiahwinfo.proto.Connections.Connection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        processName_ = "";

        protocol_ = "";

        localAddress_ = "";

        remoteAddress_ = "";

        localPort_ = 0;

        remotePort_ = 0;

        state_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_descriptor;
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.Connections.Connection getDefaultInstanceForType() {
        return info.malenkov.aspiahwinfo.proto.Connections.Connection.getDefaultInstance();
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.Connections.Connection build() {
        info.malenkov.aspiahwinfo.proto.Connections.Connection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.Connections.Connection buildPartial() {
        info.malenkov.aspiahwinfo.proto.Connections.Connection result = new info.malenkov.aspiahwinfo.proto.Connections.Connection(this);
        result.processName_ = processName_;
        result.protocol_ = protocol_;
        result.localAddress_ = localAddress_;
        result.remoteAddress_ = remoteAddress_;
        result.localPort_ = localPort_;
        result.remotePort_ = remotePort_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.malenkov.aspiahwinfo.proto.Connections.Connection) {
          return mergeFrom((info.malenkov.aspiahwinfo.proto.Connections.Connection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.Connections.Connection other) {
        if (other == info.malenkov.aspiahwinfo.proto.Connections.Connection.getDefaultInstance()) return this;
        if (!other.getProcessName().isEmpty()) {
          processName_ = other.processName_;
          onChanged();
        }
        if (!other.getProtocol().isEmpty()) {
          protocol_ = other.protocol_;
          onChanged();
        }
        if (!other.getLocalAddress().isEmpty()) {
          localAddress_ = other.localAddress_;
          onChanged();
        }
        if (!other.getRemoteAddress().isEmpty()) {
          remoteAddress_ = other.remoteAddress_;
          onChanged();
        }
        if (other.getLocalPort() != 0) {
          setLocalPort(other.getLocalPort());
        }
        if (other.getRemotePort() != 0) {
          setRemotePort(other.getRemotePort());
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.malenkov.aspiahwinfo.proto.Connections.Connection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.malenkov.aspiahwinfo.proto.Connections.Connection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object processName_ = "";
      /**
       * <code>string process_name = 1;</code>
       * @return The processName.
       */
      public java.lang.String getProcessName() {
        java.lang.Object ref = processName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          processName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string process_name = 1;</code>
       * @return The bytes for processName.
       */
      public com.google.protobuf.ByteString
          getProcessNameBytes() {
        java.lang.Object ref = processName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string process_name = 1;</code>
       * @param value The processName to set.
       * @return This builder for chaining.
       */
      public Builder setProcessName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        processName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string process_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessName() {
        
        processName_ = getDefaultInstance().getProcessName();
        onChanged();
        return this;
      }
      /**
       * <code>string process_name = 1;</code>
       * @param value The bytes for processName to set.
       * @return This builder for chaining.
       */
      public Builder setProcessNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        processName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object protocol_ = "";
      /**
       * <code>string protocol = 2;</code>
       * @return The protocol.
       */
      public java.lang.String getProtocol() {
        java.lang.Object ref = protocol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          protocol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string protocol = 2;</code>
       * @return The bytes for protocol.
       */
      public com.google.protobuf.ByteString
          getProtocolBytes() {
        java.lang.Object ref = protocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string protocol = 2;</code>
       * @param value The protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocol() {
        
        protocol_ = getDefaultInstance().getProtocol();
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 2;</code>
       * @param value The bytes for protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        protocol_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object localAddress_ = "";
      /**
       * <code>string local_address = 3;</code>
       * @return The localAddress.
       */
      public java.lang.String getLocalAddress() {
        java.lang.Object ref = localAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          localAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string local_address = 3;</code>
       * @return The bytes for localAddress.
       */
      public com.google.protobuf.ByteString
          getLocalAddressBytes() {
        java.lang.Object ref = localAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string local_address = 3;</code>
       * @param value The localAddress to set.
       * @return This builder for chaining.
       */
      public Builder setLocalAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string local_address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalAddress() {
        
        localAddress_ = getDefaultInstance().getLocalAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string local_address = 3;</code>
       * @param value The bytes for localAddress to set.
       * @return This builder for chaining.
       */
      public Builder setLocalAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remoteAddress_ = "";
      /**
       * <code>string remote_address = 4;</code>
       * @return The remoteAddress.
       */
      public java.lang.String getRemoteAddress() {
        java.lang.Object ref = remoteAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remoteAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string remote_address = 4;</code>
       * @return The bytes for remoteAddress.
       */
      public com.google.protobuf.ByteString
          getRemoteAddressBytes() {
        java.lang.Object ref = remoteAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remoteAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string remote_address = 4;</code>
       * @param value The remoteAddress to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remoteAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string remote_address = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteAddress() {
        
        remoteAddress_ = getDefaultInstance().getRemoteAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string remote_address = 4;</code>
       * @param value The bytes for remoteAddress to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remoteAddress_ = value;
        onChanged();
        return this;
      }

      private int localPort_ ;
      /**
       * <code>uint32 local_port = 5;</code>
       * @return The localPort.
       */
      @java.lang.Override
      public int getLocalPort() {
        return localPort_;
      }
      /**
       * <code>uint32 local_port = 5;</code>
       * @param value The localPort to set.
       * @return This builder for chaining.
       */
      public Builder setLocalPort(int value) {
        
        localPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 local_port = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalPort() {
        
        localPort_ = 0;
        onChanged();
        return this;
      }

      private int remotePort_ ;
      /**
       * <code>uint32 remote_port = 6;</code>
       * @return The remotePort.
       */
      @java.lang.Override
      public int getRemotePort() {
        return remotePort_;
      }
      /**
       * <code>uint32 remote_port = 6;</code>
       * @param value The remotePort to set.
       * @return This builder for chaining.
       */
      public Builder setRemotePort(int value) {
        
        remotePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 remote_port = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemotePort() {
        
        remotePort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string state = 7;</code>
       * @return The state.
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string state = 7;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string state = 7;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string state = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>string state = 7;</code>
       * @param value The bytes for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.Connections.Connection)
    }

    // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.Connections.Connection)
    private static final info.malenkov.aspiahwinfo.proto.Connections.Connection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.Connections.Connection();
    }

    public static info.malenkov.aspiahwinfo.proto.Connections.Connection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Connection>
        PARSER = new com.google.protobuf.AbstractParser<Connection>() {
      @java.lang.Override
      public Connection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Connection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Connection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Connection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Connections.Connection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int CONNECTION_FIELD_NUMBER = 1;
  private java.util.List<info.malenkov.aspiahwinfo.proto.Connections.Connection> connection_;
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
   */
  @java.lang.Override
  public java.util.List<info.malenkov.aspiahwinfo.proto.Connections.Connection> getConnectionList() {
    return connection_;
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder> 
      getConnectionOrBuilderList() {
    return connection_;
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
   */
  @java.lang.Override
  public int getConnectionCount() {
    return connection_.size();
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.Connections.Connection getConnection(int index) {
    return connection_.get(index);
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder getConnectionOrBuilder(
      int index) {
    return connection_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < connection_.size(); i++) {
      output.writeMessage(1, connection_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < connection_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, connection_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiahwinfo.proto.Connections)) {
      return super.equals(obj);
    }
    info.malenkov.aspiahwinfo.proto.Connections other = (info.malenkov.aspiahwinfo.proto.Connections) obj;

    if (!getConnectionList()
        .equals(other.getConnectionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getConnectionCount() > 0) {
      hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
      hash = (53 * hash) + getConnectionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Connections parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.Connections prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Connections}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.Connections)
      info.malenkov.aspiahwinfo.proto.ConnectionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.Connections.class, info.malenkov.aspiahwinfo.proto.Connections.Builder.class);
    }

    // Construct using info.malenkov.aspiahwinfo.proto.Connections.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConnectionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (connectionBuilder_ == null) {
        connection_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        connectionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Connections_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Connections getDefaultInstanceForType() {
      return info.malenkov.aspiahwinfo.proto.Connections.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Connections build() {
      info.malenkov.aspiahwinfo.proto.Connections result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Connections buildPartial() {
      info.malenkov.aspiahwinfo.proto.Connections result = new info.malenkov.aspiahwinfo.proto.Connections(this);
      int from_bitField0_ = bitField0_;
      if (connectionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          connection_ = java.util.Collections.unmodifiableList(connection_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.connection_ = connection_;
      } else {
        result.connection_ = connectionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiahwinfo.proto.Connections) {
        return mergeFrom((info.malenkov.aspiahwinfo.proto.Connections)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.Connections other) {
      if (other == info.malenkov.aspiahwinfo.proto.Connections.getDefaultInstance()) return this;
      if (connectionBuilder_ == null) {
        if (!other.connection_.isEmpty()) {
          if (connection_.isEmpty()) {
            connection_ = other.connection_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureConnectionIsMutable();
            connection_.addAll(other.connection_);
          }
          onChanged();
        }
      } else {
        if (!other.connection_.isEmpty()) {
          if (connectionBuilder_.isEmpty()) {
            connectionBuilder_.dispose();
            connectionBuilder_ = null;
            connection_ = other.connection_;
            bitField0_ = (bitField0_ & ~0x00000001);
            connectionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConnectionFieldBuilder() : null;
          } else {
            connectionBuilder_.addAllMessages(other.connection_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiahwinfo.proto.Connections parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiahwinfo.proto.Connections) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<info.malenkov.aspiahwinfo.proto.Connections.Connection> connection_ =
      java.util.Collections.emptyList();
    private void ensureConnectionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        connection_ = new java.util.ArrayList<info.malenkov.aspiahwinfo.proto.Connections.Connection>(connection_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiahwinfo.proto.Connections.Connection, info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder, info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder> connectionBuilder_;

    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public java.util.List<info.malenkov.aspiahwinfo.proto.Connections.Connection> getConnectionList() {
      if (connectionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(connection_);
      } else {
        return connectionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public int getConnectionCount() {
      if (connectionBuilder_ == null) {
        return connection_.size();
      } else {
        return connectionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Connections.Connection getConnection(int index) {
      if (connectionBuilder_ == null) {
        return connection_.get(index);
      } else {
        return connectionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder setConnection(
        int index, info.malenkov.aspiahwinfo.proto.Connections.Connection value) {
      if (connectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConnectionIsMutable();
        connection_.set(index, value);
        onChanged();
      } else {
        connectionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder setConnection(
        int index, info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder builderForValue) {
      if (connectionBuilder_ == null) {
        ensureConnectionIsMutable();
        connection_.set(index, builderForValue.build());
        onChanged();
      } else {
        connectionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder addConnection(info.malenkov.aspiahwinfo.proto.Connections.Connection value) {
      if (connectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConnectionIsMutable();
        connection_.add(value);
        onChanged();
      } else {
        connectionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder addConnection(
        int index, info.malenkov.aspiahwinfo.proto.Connections.Connection value) {
      if (connectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConnectionIsMutable();
        connection_.add(index, value);
        onChanged();
      } else {
        connectionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder addConnection(
        info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder builderForValue) {
      if (connectionBuilder_ == null) {
        ensureConnectionIsMutable();
        connection_.add(builderForValue.build());
        onChanged();
      } else {
        connectionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder addConnection(
        int index, info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder builderForValue) {
      if (connectionBuilder_ == null) {
        ensureConnectionIsMutable();
        connection_.add(index, builderForValue.build());
        onChanged();
      } else {
        connectionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder addAllConnection(
        java.lang.Iterable<? extends info.malenkov.aspiahwinfo.proto.Connections.Connection> values) {
      if (connectionBuilder_ == null) {
        ensureConnectionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, connection_);
        onChanged();
      } else {
        connectionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder clearConnection() {
      if (connectionBuilder_ == null) {
        connection_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        connectionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public Builder removeConnection(int index) {
      if (connectionBuilder_ == null) {
        ensureConnectionIsMutable();
        connection_.remove(index);
        onChanged();
      } else {
        connectionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder getConnectionBuilder(
        int index) {
      return getConnectionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder getConnectionOrBuilder(
        int index) {
      if (connectionBuilder_ == null) {
        return connection_.get(index);  } else {
        return connectionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public java.util.List<? extends info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder> 
         getConnectionOrBuilderList() {
      if (connectionBuilder_ != null) {
        return connectionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(connection_);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder addConnectionBuilder() {
      return getConnectionFieldBuilder().addBuilder(
          info.malenkov.aspiahwinfo.proto.Connections.Connection.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder addConnectionBuilder(
        int index) {
      return getConnectionFieldBuilder().addBuilder(
          index, info.malenkov.aspiahwinfo.proto.Connections.Connection.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Connections.Connection connection = 1;</code>
     */
    public java.util.List<info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder> 
         getConnectionBuilderList() {
      return getConnectionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiahwinfo.proto.Connections.Connection, info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder, info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder> 
        getConnectionFieldBuilder() {
      if (connectionBuilder_ == null) {
        connectionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            info.malenkov.aspiahwinfo.proto.Connections.Connection, info.malenkov.aspiahwinfo.proto.Connections.Connection.Builder, info.malenkov.aspiahwinfo.proto.Connections.ConnectionOrBuilder>(
                connection_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        connection_ = null;
      }
      return connectionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.Connections)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.Connections)
  private static final info.malenkov.aspiahwinfo.proto.Connections DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.Connections();
  }

  public static info.malenkov.aspiahwinfo.proto.Connections getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Connections>
      PARSER = new com.google.protobuf.AbstractParser<Connections>() {
    @java.lang.Override
    public Connections parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Connections(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Connections> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Connections> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.Connections getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

