// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface DriversOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.Drivers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Drivers.Driver driver = 1;</code>
   */
  java.util.List<info.malenkov.aspiahwinfo.proto.Drivers.Driver> 
      getDriverList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Drivers.Driver driver = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.Drivers.Driver getDriver(int index);
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Drivers.Driver driver = 1;</code>
   */
  int getDriverCount();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Drivers.Driver driver = 1;</code>
   */
  java.util.List<? extends info.malenkov.aspiahwinfo.proto.Drivers.DriverOrBuilder> 
      getDriverOrBuilderList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Drivers.Driver driver = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.Drivers.DriverOrBuilder getDriverOrBuilder(
      int index);
}
