// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface LogicalDrivesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.LogicalDrives)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  java.util.List<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive> 
      getDriveList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive getDrive(int index);
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  int getDriveCount();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  java.util.List<? extends info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder> 
      getDriveOrBuilderList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder getDriveOrBuilder(
      int index);
}
