// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

/**
 * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Processor}
 */
public final class Processor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.Processor)
    ProcessorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Processor.newBuilder() to construct.
  private Processor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Processor() {
    vendor_ = "";
    model_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Processor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Processor(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            vendor_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            model_ = s;
            break;
          }
          case 24: {

            packages_ = input.readUInt32();
            break;
          }
          case 32: {

            cores_ = input.readUInt32();
            break;
          }
          case 40: {

            threads_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Processor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Processor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiahwinfo.proto.Processor.class, info.malenkov.aspiahwinfo.proto.Processor.Builder.class);
  }

  public static final int VENDOR_FIELD_NUMBER = 1;
  private volatile java.lang.Object vendor_;
  /**
   * <code>string vendor = 1;</code>
   * @return The vendor.
   */
  @java.lang.Override
  public java.lang.String getVendor() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vendor_ = s;
      return s;
    }
  }
  /**
   * <code>string vendor = 1;</code>
   * @return The bytes for vendor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVendorBytes() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vendor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object model_;
  /**
   * <code>string model = 2;</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGES_FIELD_NUMBER = 3;
  private int packages_;
  /**
   * <code>uint32 packages = 3;</code>
   * @return The packages.
   */
  @java.lang.Override
  public int getPackages() {
    return packages_;
  }

  public static final int CORES_FIELD_NUMBER = 4;
  private int cores_;
  /**
   * <code>uint32 cores = 4;</code>
   * @return The cores.
   */
  @java.lang.Override
  public int getCores() {
    return cores_;
  }

  public static final int THREADS_FIELD_NUMBER = 5;
  private int threads_;
  /**
   * <code>uint32 threads = 5;</code>
   * @return The threads.
   */
  @java.lang.Override
  public int getThreads() {
    return threads_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vendor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, model_);
    }
    if (packages_ != 0) {
      output.writeUInt32(3, packages_);
    }
    if (cores_ != 0) {
      output.writeUInt32(4, cores_);
    }
    if (threads_ != 0) {
      output.writeUInt32(5, threads_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vendor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, model_);
    }
    if (packages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, packages_);
    }
    if (cores_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, cores_);
    }
    if (threads_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, threads_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiahwinfo.proto.Processor)) {
      return super.equals(obj);
    }
    info.malenkov.aspiahwinfo.proto.Processor other = (info.malenkov.aspiahwinfo.proto.Processor) obj;

    if (!getVendor()
        .equals(other.getVendor())) return false;
    if (!getModel()
        .equals(other.getModel())) return false;
    if (getPackages()
        != other.getPackages()) return false;
    if (getCores()
        != other.getCores()) return false;
    if (getThreads()
        != other.getThreads()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VENDOR_FIELD_NUMBER;
    hash = (53 * hash) + getVendor().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + PACKAGES_FIELD_NUMBER;
    hash = (53 * hash) + getPackages();
    hash = (37 * hash) + CORES_FIELD_NUMBER;
    hash = (53 * hash) + getCores();
    hash = (37 * hash) + THREADS_FIELD_NUMBER;
    hash = (53 * hash) + getThreads();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Processor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.Processor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Processor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.Processor)
      info.malenkov.aspiahwinfo.proto.ProcessorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Processor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Processor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.Processor.class, info.malenkov.aspiahwinfo.proto.Processor.Builder.class);
    }

    // Construct using info.malenkov.aspiahwinfo.proto.Processor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      vendor_ = "";

      model_ = "";

      packages_ = 0;

      cores_ = 0;

      threads_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Processor_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Processor getDefaultInstanceForType() {
      return info.malenkov.aspiahwinfo.proto.Processor.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Processor build() {
      info.malenkov.aspiahwinfo.proto.Processor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Processor buildPartial() {
      info.malenkov.aspiahwinfo.proto.Processor result = new info.malenkov.aspiahwinfo.proto.Processor(this);
      result.vendor_ = vendor_;
      result.model_ = model_;
      result.packages_ = packages_;
      result.cores_ = cores_;
      result.threads_ = threads_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiahwinfo.proto.Processor) {
        return mergeFrom((info.malenkov.aspiahwinfo.proto.Processor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.Processor other) {
      if (other == info.malenkov.aspiahwinfo.proto.Processor.getDefaultInstance()) return this;
      if (!other.getVendor().isEmpty()) {
        vendor_ = other.vendor_;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (other.getPackages() != 0) {
        setPackages(other.getPackages());
      }
      if (other.getCores() != 0) {
        setCores(other.getCores());
      }
      if (other.getThreads() != 0) {
        setThreads(other.getThreads());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiahwinfo.proto.Processor parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiahwinfo.proto.Processor) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object vendor_ = "";
    /**
     * <code>string vendor = 1;</code>
     * @return The vendor.
     */
    public java.lang.String getVendor() {
      java.lang.Object ref = vendor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vendor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vendor = 1;</code>
     * @return The bytes for vendor.
     */
    public com.google.protobuf.ByteString
        getVendorBytes() {
      java.lang.Object ref = vendor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vendor = 1;</code>
     * @param value The vendor to set.
     * @return This builder for chaining.
     */
    public Builder setVendor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vendor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vendor = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVendor() {
      
      vendor_ = getDefaultInstance().getVendor();
      onChanged();
      return this;
    }
    /**
     * <code>string vendor = 1;</code>
     * @param value The bytes for vendor to set.
     * @return This builder for chaining.
     */
    public Builder setVendorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vendor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <code>string model = 2;</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model = 2;</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2;</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private int packages_ ;
    /**
     * <code>uint32 packages = 3;</code>
     * @return The packages.
     */
    @java.lang.Override
    public int getPackages() {
      return packages_;
    }
    /**
     * <code>uint32 packages = 3;</code>
     * @param value The packages to set.
     * @return This builder for chaining.
     */
    public Builder setPackages(int value) {
      
      packages_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 packages = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackages() {
      
      packages_ = 0;
      onChanged();
      return this;
    }

    private int cores_ ;
    /**
     * <code>uint32 cores = 4;</code>
     * @return The cores.
     */
    @java.lang.Override
    public int getCores() {
      return cores_;
    }
    /**
     * <code>uint32 cores = 4;</code>
     * @param value The cores to set.
     * @return This builder for chaining.
     */
    public Builder setCores(int value) {
      
      cores_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 cores = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCores() {
      
      cores_ = 0;
      onChanged();
      return this;
    }

    private int threads_ ;
    /**
     * <code>uint32 threads = 5;</code>
     * @return The threads.
     */
    @java.lang.Override
    public int getThreads() {
      return threads_;
    }
    /**
     * <code>uint32 threads = 5;</code>
     * @param value The threads to set.
     * @return This builder for chaining.
     */
    public Builder setThreads(int value) {
      
      threads_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 threads = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreads() {
      
      threads_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.Processor)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.Processor)
  private static final info.malenkov.aspiahwinfo.proto.Processor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.Processor();
  }

  public static info.malenkov.aspiahwinfo.proto.Processor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Processor>
      PARSER = new com.google.protobuf.AbstractParser<Processor>() {
    @java.lang.Override
    public Processor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Processor(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Processor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Processor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.Processor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

