// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface ServicesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.Services)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Services.Service service = 1;</code>
   */
  java.util.List<info.malenkov.aspiahwinfo.proto.Services.Service> 
      getServiceList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Services.Service service = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.Services.Service getService(int index);
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Services.Service service = 1;</code>
   */
  int getServiceCount();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Services.Service service = 1;</code>
   */
  java.util.List<? extends info.malenkov.aspiahwinfo.proto.Services.ServiceOrBuilder> 
      getServiceOrBuilderList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Services.Service service = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.Services.ServiceOrBuilder getServiceOrBuilder(
      int index);
}
