// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface SystemInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.SystemInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.ComputerNet computer_net = 1;</code>
   * @return Whether the computerNet field is set.
   */
  boolean hasComputerNet();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.ComputerNet computer_net = 1;</code>
   * @return The computerNet.
   */
  info.malenkov.aspiahwinfo.proto.ComputerNet getComputerNet();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.ComputerNet computer_net = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.ComputerNetOrBuilder getComputerNetOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.OperatingSystem operating_system = 2;</code>
   * @return Whether the operatingSystem field is set.
   */
  boolean hasOperatingSystem();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.OperatingSystem operating_system = 2;</code>
   * @return The operatingSystem.
   */
  info.malenkov.aspiahwinfo.proto.OperatingSystem getOperatingSystem();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.OperatingSystem operating_system = 2;</code>
   */
  info.malenkov.aspiahwinfo.proto.OperatingSystemOrBuilder getOperatingSystemOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Motherboard motherboard = 3;</code>
   * @return Whether the motherboard field is set.
   */
  boolean hasMotherboard();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Motherboard motherboard = 3;</code>
   * @return The motherboard.
   */
  info.malenkov.aspiahwinfo.proto.Motherboard getMotherboard();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Motherboard motherboard = 3;</code>
   */
  info.malenkov.aspiahwinfo.proto.MotherboardOrBuilder getMotherboardOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Bios bios = 4;</code>
   * @return Whether the bios field is set.
   */
  boolean hasBios();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Bios bios = 4;</code>
   * @return The bios.
   */
  info.malenkov.aspiahwinfo.proto.Bios getBios();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Bios bios = 4;</code>
   */
  info.malenkov.aspiahwinfo.proto.BiosOrBuilder getBiosOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Processor processor = 5;</code>
   * @return Whether the processor field is set.
   */
  boolean hasProcessor();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Processor processor = 5;</code>
   * @return The processor.
   */
  info.malenkov.aspiahwinfo.proto.Processor getProcessor();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Processor processor = 5;</code>
   */
  info.malenkov.aspiahwinfo.proto.ProcessorOrBuilder getProcessorOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Memory memory = 6;</code>
   * @return Whether the memory field is set.
   */
  boolean hasMemory();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Memory memory = 6;</code>
   * @return The memory.
   */
  info.malenkov.aspiahwinfo.proto.Memory getMemory();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Memory memory = 6;</code>
   */
  info.malenkov.aspiahwinfo.proto.MemoryOrBuilder getMemoryOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.LogicalDrives logical_drives = 7;</code>
   * @return Whether the logicalDrives field is set.
   */
  boolean hasLogicalDrives();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.LogicalDrives logical_drives = 7;</code>
   * @return The logicalDrives.
   */
  info.malenkov.aspiahwinfo.proto.LogicalDrives getLogicalDrives();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.LogicalDrives logical_drives = 7;</code>
   */
  info.malenkov.aspiahwinfo.proto.LogicalDrivesOrBuilder getLogicalDrivesOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Printers printers = 8;</code>
   * @return Whether the printers field is set.
   */
  boolean hasPrinters();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Printers printers = 8;</code>
   * @return The printers.
   */
  info.malenkov.aspiahwinfo.proto.Printers getPrinters();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Printers printers = 8;</code>
   */
  info.malenkov.aspiahwinfo.proto.PrintersOrBuilder getPrintersOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.NetworkAdapters network_adapters = 9;</code>
   * @return Whether the networkAdapters field is set.
   */
  boolean hasNetworkAdapters();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.NetworkAdapters network_adapters = 9;</code>
   * @return The networkAdapters.
   */
  info.malenkov.aspiahwinfo.proto.NetworkAdapters getNetworkAdapters();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.NetworkAdapters network_adapters = 9;</code>
   */
  info.malenkov.aspiahwinfo.proto.NetworkAdaptersOrBuilder getNetworkAdaptersOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.NetworkShares network_shares = 10;</code>
   * @return Whether the networkShares field is set.
   */
  boolean hasNetworkShares();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.NetworkShares network_shares = 10;</code>
   * @return The networkShares.
   */
  info.malenkov.aspiahwinfo.proto.NetworkShares getNetworkShares();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.NetworkShares network_shares = 10;</code>
   */
  info.malenkov.aspiahwinfo.proto.NetworkSharesOrBuilder getNetworkSharesOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.WindowsDevices windows_devices = 11;</code>
   * @return Whether the windowsDevices field is set.
   */
  boolean hasWindowsDevices();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.WindowsDevices windows_devices = 11;</code>
   * @return The windowsDevices.
   */
  info.malenkov.aspiahwinfo.proto.WindowsDevices getWindowsDevices();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.WindowsDevices windows_devices = 11;</code>
   */
  info.malenkov.aspiahwinfo.proto.WindowsDevicesOrBuilder getWindowsDevicesOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.VideoAdapters video_adapters = 12;</code>
   * @return Whether the videoAdapters field is set.
   */
  boolean hasVideoAdapters();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.VideoAdapters video_adapters = 12;</code>
   * @return The videoAdapters.
   */
  info.malenkov.aspiahwinfo.proto.VideoAdapters getVideoAdapters();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.VideoAdapters video_adapters = 12;</code>
   */
  info.malenkov.aspiahwinfo.proto.VideoAdaptersOrBuilder getVideoAdaptersOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Monitors monitors = 13;</code>
   * @return Whether the monitors field is set.
   */
  boolean hasMonitors();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Monitors monitors = 13;</code>
   * @return The monitors.
   */
  info.malenkov.aspiahwinfo.proto.Monitors getMonitors();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Monitors monitors = 13;</code>
   */
  info.malenkov.aspiahwinfo.proto.MonitorsOrBuilder getMonitorsOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.PowerOptions power_options = 14;</code>
   * @return Whether the powerOptions field is set.
   */
  boolean hasPowerOptions();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.PowerOptions power_options = 14;</code>
   * @return The powerOptions.
   */
  info.malenkov.aspiahwinfo.proto.PowerOptions getPowerOptions();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.PowerOptions power_options = 14;</code>
   */
  info.malenkov.aspiahwinfo.proto.PowerOptionsOrBuilder getPowerOptionsOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Drivers drivers = 15;</code>
   * @return Whether the drivers field is set.
   */
  boolean hasDrivers();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Drivers drivers = 15;</code>
   * @return The drivers.
   */
  info.malenkov.aspiahwinfo.proto.Drivers getDrivers();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Drivers drivers = 15;</code>
   */
  info.malenkov.aspiahwinfo.proto.DriversOrBuilder getDriversOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Services services = 16;</code>
   * @return Whether the services field is set.
   */
  boolean hasServices();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Services services = 16;</code>
   * @return The services.
   */
  info.malenkov.aspiahwinfo.proto.Services getServices();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Services services = 16;</code>
   */
  info.malenkov.aspiahwinfo.proto.ServicesOrBuilder getServicesOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EnvironmentVariables env_vars = 17;</code>
   * @return Whether the envVars field is set.
   */
  boolean hasEnvVars();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EnvironmentVariables env_vars = 17;</code>
   * @return The envVars.
   */
  info.malenkov.aspiahwinfo.proto.EnvironmentVariables getEnvVars();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EnvironmentVariables env_vars = 17;</code>
   */
  info.malenkov.aspiahwinfo.proto.EnvironmentVariablesOrBuilder getEnvVarsOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogs event_logs = 18;</code>
   * @return Whether the eventLogs field is set.
   */
  boolean hasEventLogs();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogs event_logs = 18;</code>
   * @return The eventLogs.
   */
  info.malenkov.aspiahwinfo.proto.EventLogs getEventLogs();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogs event_logs = 18;</code>
   */
  info.malenkov.aspiahwinfo.proto.EventLogsOrBuilder getEventLogsOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Routes routes = 19;</code>
   * @return Whether the routes field is set.
   */
  boolean hasRoutes();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Routes routes = 19;</code>
   * @return The routes.
   */
  info.malenkov.aspiahwinfo.proto.Routes getRoutes();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Routes routes = 19;</code>
   */
  info.malenkov.aspiahwinfo.proto.RoutesOrBuilder getRoutesOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Connections connections = 20;</code>
   * @return Whether the connections field is set.
   */
  boolean hasConnections();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Connections connections = 20;</code>
   * @return The connections.
   */
  info.malenkov.aspiahwinfo.proto.Connections getConnections();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Connections connections = 20;</code>
   */
  info.malenkov.aspiahwinfo.proto.ConnectionsOrBuilder getConnectionsOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Licenses licenses = 21;</code>
   * @return Whether the licenses field is set.
   */
  boolean hasLicenses();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Licenses licenses = 21;</code>
   * @return The licenses.
   */
  info.malenkov.aspiahwinfo.proto.Licenses getLicenses();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Licenses licenses = 21;</code>
   */
  info.malenkov.aspiahwinfo.proto.LicensesOrBuilder getLicensesOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Applications applications = 22;</code>
   * @return Whether the applications field is set.
   */
  boolean hasApplications();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Applications applications = 22;</code>
   * @return The applications.
   */
  info.malenkov.aspiahwinfo.proto.Applications getApplications();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Applications applications = 22;</code>
   */
  info.malenkov.aspiahwinfo.proto.ApplicationsOrBuilder getApplicationsOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.OpenFiles open_files = 23;</code>
   * @return Whether the openFiles field is set.
   */
  boolean hasOpenFiles();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.OpenFiles open_files = 23;</code>
   * @return The openFiles.
   */
  info.malenkov.aspiahwinfo.proto.OpenFiles getOpenFiles();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.OpenFiles open_files = 23;</code>
   */
  info.malenkov.aspiahwinfo.proto.OpenFilesOrBuilder getOpenFilesOrBuilder();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.SystemInfoFooter footer = 128000;</code>
   * @return Whether the footer field is set.
   */
  boolean hasFooter();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.SystemInfoFooter footer = 128000;</code>
   * @return The footer.
   */
  info.malenkov.aspiahwinfo.proto.SystemInfoFooter getFooter();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.SystemInfoFooter footer = 128000;</code>
   */
  info.malenkov.aspiahwinfo.proto.SystemInfoFooterOrBuilder getFooterOrBuilder();
}
