// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public final class AspiaSystemInfo {
  private AspiaSystemInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_ComputerNet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_ComputerNet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_OperatingSystem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_OperatingSystem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Motherboard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Motherboard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Bios_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Bios_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Processor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Processor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Memory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Memory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Memory_Module_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Memory_Module_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Printers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Printers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_Share_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_Share_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_Adapter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_Adapter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Monitors_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_Timing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_Timing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_Battery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_Battery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Drivers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Drivers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Drivers_Driver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Drivers_Driver_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Services_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Services_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Services_Service_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Services_Service_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_Variable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_Variable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_EventLogsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Routes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Routes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Routes_Route_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Routes_Route_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Connections_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Connections_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Licenses_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_Field_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_Field_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Applications_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Applications_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_Applications_Application_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_Applications_Application_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_OpenFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_OpenFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoFooter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoFooter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiahwinfo_proto_SystemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027aspia.system_info.proto\022\037info.malenkov" +
      ".aspiahwinfo.proto\"N\n\013ComputerNet\022\014\n\004nam" +
      "e\030\001 \001(\t\022\016\n\006domain\030\002 \001(\t\022\021\n\tworkgroup\030\003 \001" +
      "(\t\022\016\n\006uptime\030\004 \001(\004\"a\n\017OperatingSystem\022\014\n" +
      "\004name\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\014\n\004arch\030\003 \001" +
      "(\t\022\013\n\003key\030\004 \001(\t\022\024\n\014install_date\030\005 \001(\003\"2\n" +
      "\013Motherboard\022\024\n\014manufacturer\030\001 \001(\t\022\r\n\005mo" +
      "del\030\002 \001(\t\"5\n\004Bios\022\016\n\006vendor\030\001 \001(\t\022\017\n\007ver" +
      "sion\030\002 \001(\t\022\014\n\004date\030\003 \001(\t\"\\\n\tProcessor\022\016\n" +
      "\006vendor\030\001 \001(\t\022\r\n\005model\030\002 \001(\t\022\020\n\010packages" +
      "\030\003 \001(\r\022\r\n\005cores\030\004 \001(\r\022\017\n\007threads\030\005 \001(\r\"\341" +
      "\001\n\006Memory\022>\n\006module\030\001 \003(\0132..info.malenko" +
      "v.aspiahwinfo.proto.Memory.Module\032\226\001\n\006Mo" +
      "dule\022\017\n\007present\030\001 \001(\010\022\020\n\010location\030\002 \001(\t\022" +
      "\024\n\014manufacturer\030\003 \001(\t\022\014\n\004size\030\004 \001(\004\022\014\n\004t" +
      "ype\030\005 \001(\t\022\023\n\013form_factor\030\006 \001(\t\022\023\n\013part_n" +
      "umber\030\007 \001(\t\022\r\n\005speed\030\010 \001(\r\"\247\001\n\rLogicalDr" +
      "ives\022C\n\005drive\030\001 \003(\01324.info.malenkov.aspi" +
      "ahwinfo.proto.LogicalDrives.Drive\032Q\n\005Dri" +
      "ve\022\014\n\004path\030\001 \001(\t\022\023\n\013file_system\030\002 \001(\t\022\022\n" +
      "\ntotal_size\030\003 \001(\004\022\021\n\tfree_size\030\004 \001(\004\"\316\001\n" +
      "\010Printers\022B\n\007printer\030\001 \003(\01321.info.malenk" +
      "ov.aspiahwinfo.proto.Printers.Printer\032~\n" +
      "\007Printer\022\014\n\004name\030\001 \001(\t\022\017\n\007default\030\002 \001(\010\022" +
      "\016\n\006shared\030\003 \001(\010\022\014\n\004port\030\004 \001(\t\022\016\n\006driver\030" +
      "\005 \001(\t\022\022\n\njobs_count\030\006 \001(\r\022\022\n\nshare_name\030" +
      "\007 \001(\t\"\374\002\n\017NetworkAdapters\022I\n\007adapter\030\001 \003" +
      "(\01328.info.malenkov.aspiahwinfo.proto.Net" +
      "workAdapters.Adapter\032\235\002\n\007Adapter\022\024\n\014adap" +
      "ter_name\030\001 \001(\t\022\027\n\017connection_name\030\002 \001(\t\022" +
      "\r\n\005iface\030\003 \001(\t\022\r\n\005speed\030\004 \001(\004\022\013\n\003mac\030\005 \001" +
      "(\t\022\024\n\014dhcp_enabled\030\006 \001(\010\022\017\n\007gateway\030\007 \003(" +
      "\t\022Q\n\007address\030\010 \003(\0132@.info.malenkov.aspia" +
      "hwinfo.proto.NetworkAdapters.Adapter.Add" +
      "ress\022\013\n\003dns\030\t \003(\t\022\014\n\004dhcp\030\n \003(\t\032#\n\007Addre" +
      "ss\022\n\n\002ip\030\001 \001(\t\022\014\n\004mask\030\002 \001(\t\"\312\001\n\rNetwork" +
      "Shares\022C\n\005share\030\001 \003(\01324.info.malenkov.as" +
      "piahwinfo.proto.NetworkShares.Share\032t\n\005S" +
      "hare\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022" +
      "\014\n\004type\030\003 \001(\t\022\022\n\nlocal_path\030\004 \001(\t\022\024\n\014cur" +
      "rent_uses\030\005 \001(\r\022\020\n\010max_uses\030\006 \001(\r\"\346\001\n\016Wi" +
      "ndowsDevices\022F\n\006device\030\001 \003(\01326.info.male" +
      "nkov.aspiahwinfo.proto.WindowsDevices.De" +
      "vice\032\213\001\n\006Device\022\025\n\rfriendly_name\030\001 \001(\t\022\023" +
      "\n\013description\030\002 \001(\t\022\026\n\016driver_version\030\003 " +
      "\001(\t\022\023\n\013driver_date\030\004 \001(\t\022\025\n\rdriver_vendo" +
      "r\030\005 \001(\t\022\021\n\tdevice_id\030\006 \001(\t\"\246\002\n\rVideoAdap" +
      "ters\022G\n\007adapter\030\001 \003(\01326.info.malenkov.as" +
      "piahwinfo.proto.VideoAdapters.Adapter\032\313\001" +
      "\n\007Adapter\022\023\n\013description\030\001 \001(\t\022\026\n\016adapte" +
      "r_string\030\002 \001(\t\022\023\n\013bios_string\030\003 \001(\t\022\021\n\tc" +
      "hip_type\030\004 \001(\t\022\020\n\010dac_type\030\005 \001(\t\022\023\n\013driv" +
      "er_date\030\006 \001(\t\022\026\n\016driver_version\030\007 \001(\t\022\027\n" +
      "\017driver_provider\030\010 \001(\t\022\023\n\013memory_size\030\t " +
      "\001(\004\"\350\010\n\010Monitors\022B\n\007monitor\030\001 \003(\01321.info" +
      ".malenkov.aspiahwinfo.proto.Monitors.Mon" +
      "itor\032\227\010\n\007Monitor\022\023\n\013system_name\030\001 \001(\t\022\024\n" +
      "\014monitor_name\030\002 \001(\t\022\031\n\021manufacturer_name" +
      "\030\003 \001(\t\022\022\n\nmonitor_id\030\004 \001(\t\022\025\n\rserial_num" +
      "ber\030\005 \001(\t\022\024\n\014edid_version\030\006 \001(\005\022\025\n\redid_" +
      "revision\030\007 \001(\005\022\033\n\023week_of_manufacture\030\010 " +
      "\001(\005\022\033\n\023year_of_manufacture\030\t \001(\005\022!\n\031max_" +
      "horizontal_image_size\030\n \001(\005\022\037\n\027max_verti" +
      "cal_image_size\030\013 \001(\005\022\035\n\025horizontal_resol" +
      "ution\030\014 \001(\005\022\034\n\024vertical_resoulution\030\r \001(" +
      "\005\022\r\n\005gamma\030\016 \001(\001\022\033\n\023min_horizontal_rate\030" +
      "\017 \001(\005\022\033\n\023max_horizontal_rate\030\020 \001(\005\022\031\n\021mi" +
      "n_vertical_rate\030\021 \001(\005\022\031\n\021max_vertical_ra" +
      "te\030\022 \001(\005\022\023\n\013pixel_clock\030\023 \001(\001\022\027\n\017max_pix" +
      "el_clock\030\024 \001(\005\022\\\n\021input_signal_type\030\025 \001(" +
      "\0162A.info.malenkov.aspiahwinfo.proto.Moni" +
      "tors.Monitor.InputSignalType\022\035\n\025default_" +
      "gtf_supported\030\026 \001(\010\022\031\n\021suspend_supported" +
      "\030\027 \001(\010\022\031\n\021standby_supported\030\030 \001(\010\022\034\n\024act" +
      "ive_off_supported\030\031 \001(\010\022\'\n\037preferred_tim" +
      "ing_mode_supported\030\032 \001(\010\022\026\n\016srgb_support" +
      "ed\030\033 \001(\010\022I\n\007timings\030\034 \003(\01328.info.malenko" +
      "v.aspiahwinfo.proto.Monitors.Monitor.Tim" +
      "ing\032:\n\006Timing\022\r\n\005width\030\001 \001(\005\022\016\n\006height\030\002" +
      " \001(\005\022\021\n\tfrequency\030\003 \001(\005\"m\n\017InputSignalTy" +
      "pe\022\035\n\031INPUT_SIGNAL_TYPE_UNKNOWN\020\000\022\034\n\030INP" +
      "UT_SIGNAL_TYPE_ANALOG\020\001\022\035\n\031INPUT_SIGNAL_" +
      "TYPE_DIGITAL\020\002\"\220\010\n\014PowerOptions\022O\n\014power" +
      "_source\030\001 \001(\01629.info.malenkov.aspiahwinf" +
      "o.proto.PowerOptions.PowerSource\022S\n\016batt" +
      "ery_status\030\002 \001(\0162;.info.malenkov.aspiahw" +
      "info.proto.PowerOptions.BatteryStatus\022\036\n" +
      "\026full_battery_life_time\030\003 \001(\004\022#\n\033remaini" +
      "ng_battery_life_time\030\004 \001(\004\022\034\n\024battery_li" +
      "fe_percent\030\005 \001(\r\022F\n\007battery\030\006 \003(\01325.info" +
      ".malenkov.aspiahwinfo.proto.PowerOptions" +
      ".Battery\032\226\003\n\007Battery\022\023\n\013device_name\030\001 \001(" +
      "\t\022\024\n\014manufacturer\030\002 \001(\t\022\030\n\020manufacture_d" +
      "ate\030\003 \001(\t\022\021\n\tunique_id\030\004 \001(\t\022\025\n\rserial_n" +
      "umber\030\005 \001(\t\022\023\n\013temperature\030\006 \001(\t\022\027\n\017desi" +
      "gn_capacity\030\007 \001(\r\022\014\n\004type\030\010 \001(\t\022\035\n\025full_" +
      "charged_capacity\030\t \001(\r\022\024\n\014depreciation\030\n" +
      " \001(\r\022\030\n\020current_capacity\030\013 \001(\r\022\017\n\007voltag" +
      "e\030\014 \001(\r\022\r\n\005state\030\r \001(\r\"q\n\005State\022\021\n\rSTATE" +
      "_UNKNOWN\020\000\022\022\n\016STATE_CHARGING\020\001\022\022\n\016STATE_" +
      "CRITICAL\020\002\022\025\n\021STATE_DISCHARGING\020\004\022\026\n\022STA" +
      "TE_POWER_ONLINE\020\010\"^\n\013PowerSource\022\030\n\024POWE" +
      "R_SOURCE_UNKNOWN\020\000\022\033\n\027POWER_SOURCE_DC_BA" +
      "TTERY\020\001\022\030\n\024POWER_SOURCE_AC_LINE\020\002\"\265\001\n\rBa" +
      "tteryStatus\022\032\n\026BATTERY_STATUS_UNKNOWN\020\000\022" +
      "\027\n\023BATTERY_STATUS_HIGH\020\001\022\026\n\022BATTERY_STAT" +
      "US_LOW\020\002\022\033\n\027BATTERY_STATUS_CRITICAL\020\003\022\033\n" +
      "\027BATTERY_STATUS_CHARGING\020\004\022\035\n\031BATTERY_ST" +
      "ATUS_NO_BATTERY\020\005\"\277\005\n\007Drivers\022?\n\006driver\030" +
      "\001 \003(\0132/.info.malenkov.aspiahwinfo.proto." +
      "Drivers.Driver\032\362\004\n\006Driver\022\014\n\004name\030\001 \001(\t\022" +
      "\024\n\014display_name\030\002 \001(\t\022\023\n\013description\030\003 \001" +
      "(\t\022F\n\006status\030\004 \001(\01626.info.malenkov.aspia" +
      "hwinfo.proto.Drivers.Driver.Status\022Q\n\014st" +
      "artup_type\030\005 \001(\0162;.info.malenkov.aspiahw" +
      "info.proto.Drivers.Driver.StartupType\022\023\n" +
      "\013binary_path\030\006 \001(\t\"\301\001\n\006Status\022\022\n\016STATUS_" +
      "UNKNOWN\020\000\022\033\n\027STATUS_CONTINUE_PENDING\020\001\022\030" +
      "\n\024STATUS_PAUSE_PENDING\020\002\022\021\n\rSTATUS_PAUSE" +
      "D\020\003\022\022\n\016STATUS_RUNNING\020\004\022\030\n\024STATUS_START_" +
      "PENDING\020\005\022\027\n\023STATUS_STOP_PENDING\020\006\022\022\n\016ST" +
      "ATUS_STOPPED\020\007\"\272\001\n\013StartupType\022\030\n\024STARTU" +
      "P_TYPE_UNKNOWN\020\000\022\033\n\027STARTUP_TYPE_AUTO_ST" +
      "ART\020\001\022\035\n\031STARTUP_TYPE_DEMAND_START\020\002\022\031\n\025" +
      "STARTUP_TYPE_DISABLED\020\003\022\033\n\027STARTUP_TYPE_" +
      "BOOT_START\020\004\022\035\n\031STARTUP_TYPE_SYSTEM_STAR" +
      "T\020\005\"\334\005\n\010Services\022B\n\007service\030\001 \003(\01321.info" +
      ".malenkov.aspiahwinfo.proto.Services.Ser" +
      "vice\032\213\005\n\007Service\022\014\n\004name\030\001 \001(\t\022\024\n\014displa" +
      "y_name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022H\n\006sta" +
      "tus\030\004 \001(\01628.info.malenkov.aspiahwinfo.pr" +
      "oto.Services.Service.Status\022S\n\014startup_t" +
      "ype\030\005 \001(\0162=.info.malenkov.aspiahwinfo.pr" +
      "oto.Services.Service.StartupType\022\023\n\013bina" +
      "ry_path\030\006 \001(\t\022\022\n\nstart_name\030\007 \001(\t\"\301\001\n\006St" +
      "atus\022\022\n\016STATUS_UNKNOWN\020\000\022\033\n\027STATUS_CONTI" +
      "NUE_PENDING\020\001\022\030\n\024STATUS_PAUSE_PENDING\020\002\022" +
      "\021\n\rSTATUS_PAUSED\020\003\022\022\n\016STATUS_RUNNING\020\004\022\030" +
      "\n\024STATUS_START_PENDING\020\005\022\027\n\023STATUS_STOP_" +
      "PENDING\020\006\022\022\n\016STATUS_STOPPED\020\007\"\272\001\n\013Startu" +
      "pType\022\030\n\024STARTUP_TYPE_UNKNOWN\020\000\022\033\n\027START" +
      "UP_TYPE_AUTO_START\020\001\022\035\n\031STARTUP_TYPE_DEM" +
      "AND_START\020\002\022\031\n\025STARTUP_TYPE_DISABLED\020\003\022\033" +
      "\n\027STARTUP_TYPE_BOOT_START\020\004\022\035\n\031STARTUP_T" +
      "YPE_SYSTEM_START\020\005\"\221\001\n\024EnvironmentVariab" +
      "les\022P\n\010variable\030\001 \003(\0132>.info.malenkov.as" +
      "piahwinfo.proto.EnvironmentVariables.Var" +
      "iable\032\'\n\010Variable\022\014\n\004name\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t\"\301\004\n\tEventLogs\022C\n\004type\030\001 \001(\01625.inf" +
      "o.malenkov.aspiahwinfo.proto.EventLogs.E" +
      "vent.Type\022\025\n\rtotal_records\030\002 \001(\r\022?\n\005even" +
      "t\030\003 \003(\01320.info.malenkov.aspiahwinfo.prot" +
      "o.EventLogs.Event\032\226\003\n\005Event\022E\n\005level\030\001 \001" +
      "(\01626.info.malenkov.aspiahwinfo.proto.Eve" +
      "ntLogs.Event.Level\022\014\n\004time\030\002 \001(\003\022\020\n\010cate" +
      "gory\030\003 \001(\t\022\020\n\010event_id\030\004 \001(\r\022\016\n\006source\030\005" +
      " \001(\t\022\023\n\013description\030\006 \001(\t\"R\n\004Type\022\020\n\014TYP" +
      "E_UNKNOWN\020\000\022\024\n\020TYPE_APPLICATION\020\001\022\021\n\rTYP" +
      "E_SECURITY\020\002\022\017\n\013TYPE_SYSTEM\020\003\"\232\001\n\005Level\022" +
      "\021\n\rLEVEL_UNKNOWN\020\000\022\021\n\rLEVEL_SUCCESS\020\001\022\025\n" +
      "\021LEVEL_INFORMATION\020\002\022\021\n\rLEVEL_WARNING\020\004\022" +
      "\017\n\013LEVEL_ERROR\020\010\022\027\n\023LEVEL_AUDIT_SUCCESS\020" +
      "\020\022\027\n\023LEVEL_AUDIT_FAILURE\020 \"\200\001\n\rEventLogs" +
      "Data\022C\n\004type\030\001 \001(\01625.info.malenkov.aspia" +
      "hwinfo.proto.EventLogs.Event.Type\022\024\n\014rec" +
      "ord_start\030\002 \001(\r\022\024\n\014record_count\030\003 \001(\r\"\223\001" +
      "\n\006Routes\022<\n\005route\030\001 \003(\0132-.info.malenkov." +
      "aspiahwinfo.proto.Routes.Route\032K\n\005Route\022" +
      "\023\n\013destonation\030\001 \001(\t\022\014\n\004mask\030\002 \001(\t\022\017\n\007ga" +
      "teway\030\003 \001(\t\022\016\n\006metric\030\004 \001(\r\"\370\001\n\013Connecti" +
      "ons\022K\n\nconnection\030\001 \003(\01327.info.malenkov." +
      "aspiahwinfo.proto.Connections.Connection" +
      "\032\233\001\n\nConnection\022\024\n\014process_name\030\001 \001(\t\022\020\n" +
      "\010protocol\030\002 \001(\t\022\025\n\rlocal_address\030\003 \001(\t\022\026" +
      "\n\016remote_address\030\004 \001(\t\022\022\n\nlocal_port\030\005 \001" +
      "(\r\022\023\n\013remote_port\030\006 \001(\r\022\r\n\005state\030\007 \001(\t\"\273" +
      "\003\n\010Licenses\022B\n\007license\030\001 \003(\01321.info.male" +
      "nkov.aspiahwinfo.proto.Licenses.License\032" +
      "\352\002\n\007License\022\024\n\014product_name\030\001 \001(\t\022F\n\005fie" +
      "ld\030\002 \003(\01327.info.malenkov.aspiahwinfo.pro" +
      "to.Licenses.License.Field\032\200\002\n\005Field\022J\n\004t" +
      "ype\030\001 \001(\0162<.info.malenkov.aspiahwinfo.pr" +
      "oto.Licenses.License.Field.Type\022\r\n\005value" +
      "\030\002 \001(\t\"\233\001\n\004Type\022\020\n\014TYPE_UNKNOWN\020\000\022\016\n\nTYP" +
      "E_OWNER\020\002\022\025\n\021TYPE_ORGANIZATION\020\003\022\024\n\020TYPE" +
      "_PRODUCT_KEY\020\004\022\023\n\017TYPE_PRODUCT_ID\020\005\022\030\n\024T" +
      "YPE_LICENSE_VERSION\020\006\022\025\n\021TYPE_LICENSE_TY" +
      "PE\020\007\"\317\001\n\014Applications\022N\n\013application\030\001 \003" +
      "(\01329.info.malenkov.aspiahwinfo.proto.App" +
      "lications.Application\032o\n\013Application\022\014\n\004" +
      "name\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\021\n\tpublisher" +
      "\030\003 \001(\t\022\024\n\014install_date\030\004 \001(\t\022\030\n\020install_" +
      "location\030\005 \001(\t\"\245\001\n\tOpenFiles\022F\n\topen_fil" +
      "e\030\001 \003(\01323.info.malenkov.aspiahwinfo.prot" +
      "o.OpenFiles.OpenFile\032P\n\010OpenFile\022\n\n\002id\030\001" +
      " \001(\r\022\021\n\tuser_name\030\002 \001(\t\022\022\n\nlock_count\030\003 " +
      "\001(\r\022\021\n\tfile_path\030\004 \001(\t\"n\n\021SystemInfoRequ" +
      "est\022\020\n\010category\030\001 \001(\t\022G\n\017event_logs_data" +
      "\030\013 \001(\0132..info.malenkov.aspiahwinfo.proto" +
      ".EventLogsData\"$\n\020SystemInfoFooter\022\020\n\010ca" +
      "tegory\030\001 \001(\t\"\276\014\n\nSystemInfo\022B\n\014computer_" +
      "net\030\001 \001(\0132,.info.malenkov.aspiahwinfo.pr" +
      "oto.ComputerNet\022J\n\020operating_system\030\002 \001(" +
      "\01320.info.malenkov.aspiahwinfo.proto.Oper" +
      "atingSystem\022A\n\013motherboard\030\003 \001(\0132,.info." +
      "malenkov.aspiahwinfo.proto.Motherboard\0223" +
      "\n\004bios\030\004 \001(\0132%.info.malenkov.aspiahwinfo" +
      ".proto.Bios\022=\n\tprocessor\030\005 \001(\0132*.info.ma" +
      "lenkov.aspiahwinfo.proto.Processor\0227\n\006me" +
      "mory\030\006 \001(\0132\'.info.malenkov.aspiahwinfo.p" +
      "roto.Memory\022F\n\016logical_drives\030\007 \001(\0132..in" +
      "fo.malenkov.aspiahwinfo.proto.LogicalDri" +
      "ves\022;\n\010printers\030\010 \001(\0132).info.malenkov.as" +
      "piahwinfo.proto.Printers\022J\n\020network_adap" +
      "ters\030\t \001(\01320.info.malenkov.aspiahwinfo.p" +
      "roto.NetworkAdapters\022F\n\016network_shares\030\n" +
      " \001(\0132..info.malenkov.aspiahwinfo.proto.N" +
      "etworkShares\022H\n\017windows_devices\030\013 \001(\0132/." +
      "info.malenkov.aspiahwinfo.proto.WindowsD" +
      "evices\022F\n\016video_adapters\030\014 \001(\0132..info.ma" +
      "lenkov.aspiahwinfo.proto.VideoAdapters\022;" +
      "\n\010monitors\030\r \001(\0132).info.malenkov.aspiahw" +
      "info.proto.Monitors\022D\n\rpower_options\030\016 \001" +
      "(\0132-.info.malenkov.aspiahwinfo.proto.Pow" +
      "erOptions\0229\n\007drivers\030\017 \001(\0132(.info.malenk" +
      "ov.aspiahwinfo.proto.Drivers\022;\n\010services" +
      "\030\020 \001(\0132).info.malenkov.aspiahwinfo.proto" +
      ".Services\022G\n\010env_vars\030\021 \001(\01325.info.malen" +
      "kov.aspiahwinfo.proto.EnvironmentVariabl" +
      "es\022>\n\nevent_logs\030\022 \001(\0132*.info.malenkov.a" +
      "spiahwinfo.proto.EventLogs\0227\n\006routes\030\023 \001" +
      "(\0132\'.info.malenkov.aspiahwinfo.proto.Rou" +
      "tes\022A\n\013connections\030\024 \001(\0132,.info.malenkov" +
      ".aspiahwinfo.proto.Connections\022;\n\010licens" +
      "es\030\025 \001(\0132).info.malenkov.aspiahwinfo.pro" +
      "to.Licenses\022C\n\014applications\030\026 \001(\0132-.info" +
      ".malenkov.aspiahwinfo.proto.Applications" +
      "\022>\n\nopen_files\030\027 \001(\0132*.info.malenkov.asp" +
      "iahwinfo.proto.OpenFiles\022C\n\006footer\030\200\350\007 \001" +
      "(\01321.info.malenkov.aspiahwinfo.proto.Sys" +
      "temInfoFooterB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_info_malenkov_aspiahwinfo_proto_ComputerNet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_ComputerNet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_ComputerNet_descriptor,
        new java.lang.String[] { "Name", "Domain", "Workgroup", "Uptime", });
    internal_static_info_malenkov_aspiahwinfo_proto_OperatingSystem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_info_malenkov_aspiahwinfo_proto_OperatingSystem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_OperatingSystem_descriptor,
        new java.lang.String[] { "Name", "Version", "Arch", "Key", "InstallDate", });
    internal_static_info_malenkov_aspiahwinfo_proto_Motherboard_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_info_malenkov_aspiahwinfo_proto_Motherboard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Motherboard_descriptor,
        new java.lang.String[] { "Manufacturer", "Model", });
    internal_static_info_malenkov_aspiahwinfo_proto_Bios_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_info_malenkov_aspiahwinfo_proto_Bios_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Bios_descriptor,
        new java.lang.String[] { "Vendor", "Version", "Date", });
    internal_static_info_malenkov_aspiahwinfo_proto_Processor_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_info_malenkov_aspiahwinfo_proto_Processor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Processor_descriptor,
        new java.lang.String[] { "Vendor", "Model", "Packages", "Cores", "Threads", });
    internal_static_info_malenkov_aspiahwinfo_proto_Memory_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_info_malenkov_aspiahwinfo_proto_Memory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Memory_descriptor,
        new java.lang.String[] { "Module", });
    internal_static_info_malenkov_aspiahwinfo_proto_Memory_Module_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Memory_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Memory_Module_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Memory_Module_descriptor,
        new java.lang.String[] { "Present", "Location", "Manufacturer", "Size", "Type", "FormFactor", "PartNumber", "Speed", });
    internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_descriptor,
        new java.lang.String[] { "Drive", });
    internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_descriptor,
        new java.lang.String[] { "Path", "FileSystem", "TotalSize", "FreeSize", });
    internal_static_info_malenkov_aspiahwinfo_proto_Printers_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_info_malenkov_aspiahwinfo_proto_Printers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Printers_descriptor,
        new java.lang.String[] { "Printer", });
    internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Printers_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_descriptor,
        new java.lang.String[] { "Name", "Default", "Shared", "Port", "Driver", "JobsCount", "ShareName", });
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_descriptor,
        new java.lang.String[] { "Adapter", });
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_descriptor,
        new java.lang.String[] { "AdapterName", "ConnectionName", "Iface", "Speed", "Mac", "DhcpEnabled", "Gateway", "Address", "Dns", "Dhcp", });
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_Address_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_NetworkAdapters_Adapter_Address_descriptor,
        new java.lang.String[] { "Ip", "Mask", });
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_descriptor,
        new java.lang.String[] { "Share", });
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_Share_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_Share_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_NetworkShares_Share_descriptor,
        new java.lang.String[] { "Name", "Description", "Type", "LocalPath", "CurrentUses", "MaxUses", });
    internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_descriptor,
        new java.lang.String[] { "Device", });
    internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_Device_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_WindowsDevices_Device_descriptor,
        new java.lang.String[] { "FriendlyName", "Description", "DriverVersion", "DriverDate", "DriverVendor", "DeviceId", });
    internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_descriptor,
        new java.lang.String[] { "Adapter", });
    internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_Adapter_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_Adapter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_VideoAdapters_Adapter_descriptor,
        new java.lang.String[] { "Description", "AdapterString", "BiosString", "ChipType", "DacType", "DriverDate", "DriverVersion", "DriverProvider", "MemorySize", });
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Monitors_descriptor,
        new java.lang.String[] { "Monitor", });
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Monitors_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_descriptor,
        new java.lang.String[] { "SystemName", "MonitorName", "ManufacturerName", "MonitorId", "SerialNumber", "EdidVersion", "EdidRevision", "WeekOfManufacture", "YearOfManufacture", "MaxHorizontalImageSize", "MaxVerticalImageSize", "HorizontalResolution", "VerticalResoulution", "Gamma", "MinHorizontalRate", "MaxHorizontalRate", "MinVerticalRate", "MaxVerticalRate", "PixelClock", "MaxPixelClock", "InputSignalType", "DefaultGtfSupported", "SuspendSupported", "StandbySupported", "ActiveOffSupported", "PreferredTimingModeSupported", "SrgbSupported", "Timings", });
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_Timing_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_Timing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Monitors_Monitor_Timing_descriptor,
        new java.lang.String[] { "Width", "Height", "Frequency", });
    internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_descriptor,
        new java.lang.String[] { "PowerSource", "BatteryStatus", "FullBatteryLifeTime", "RemainingBatteryLifeTime", "BatteryLifePercent", "Battery", });
    internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_Battery_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_Battery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_PowerOptions_Battery_descriptor,
        new java.lang.String[] { "DeviceName", "Manufacturer", "ManufactureDate", "UniqueId", "SerialNumber", "Temperature", "DesignCapacity", "Type", "FullChargedCapacity", "Depreciation", "CurrentCapacity", "Voltage", "State", });
    internal_static_info_malenkov_aspiahwinfo_proto_Drivers_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_info_malenkov_aspiahwinfo_proto_Drivers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Drivers_descriptor,
        new java.lang.String[] { "Driver", });
    internal_static_info_malenkov_aspiahwinfo_proto_Drivers_Driver_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Drivers_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Drivers_Driver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Drivers_Driver_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "Description", "Status", "StartupType", "BinaryPath", });
    internal_static_info_malenkov_aspiahwinfo_proto_Services_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_info_malenkov_aspiahwinfo_proto_Services_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Services_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_info_malenkov_aspiahwinfo_proto_Services_Service_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Services_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Services_Service_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Services_Service_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "Description", "Status", "StartupType", "BinaryPath", "StartName", });
    internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_descriptor,
        new java.lang.String[] { "Variable", });
    internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_Variable_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_Variable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_EnvironmentVariables_Variable_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_descriptor,
        new java.lang.String[] { "Type", "TotalRecords", "Event", });
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_Event_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_EventLogs_Event_descriptor,
        new java.lang.String[] { "Level", "Time", "Category", "EventId", "Source", "Description", });
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogsData_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_info_malenkov_aspiahwinfo_proto_EventLogsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_EventLogsData_descriptor,
        new java.lang.String[] { "Type", "RecordStart", "RecordCount", });
    internal_static_info_malenkov_aspiahwinfo_proto_Routes_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_info_malenkov_aspiahwinfo_proto_Routes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Routes_descriptor,
        new java.lang.String[] { "Route", });
    internal_static_info_malenkov_aspiahwinfo_proto_Routes_Route_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Routes_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Routes_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Routes_Route_descriptor,
        new java.lang.String[] { "Destonation", "Mask", "Gateway", "Metric", });
    internal_static_info_malenkov_aspiahwinfo_proto_Connections_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_info_malenkov_aspiahwinfo_proto_Connections_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Connections_descriptor,
        new java.lang.String[] { "Connection", });
    internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Connections_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Connections_Connection_descriptor,
        new java.lang.String[] { "ProcessName", "Protocol", "LocalAddress", "RemoteAddress", "LocalPort", "RemotePort", "State", });
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Licenses_descriptor,
        new java.lang.String[] { "License", });
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Licenses_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_descriptor,
        new java.lang.String[] { "ProductName", "Field", });
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_Field_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Licenses_License_Field_descriptor,
        new java.lang.String[] { "Type", "Value", });
    internal_static_info_malenkov_aspiahwinfo_proto_Applications_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_info_malenkov_aspiahwinfo_proto_Applications_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Applications_descriptor,
        new java.lang.String[] { "Application", });
    internal_static_info_malenkov_aspiahwinfo_proto_Applications_Application_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_Applications_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_Applications_Application_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_Applications_Application_descriptor,
        new java.lang.String[] { "Name", "Version", "Publisher", "InstallDate", "InstallLocation", });
    internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_descriptor,
        new java.lang.String[] { "OpenFile", });
    internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_OpenFile_descriptor =
      internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_descriptor.getNestedTypes().get(0);
    internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_OpenFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_OpenFiles_OpenFile_descriptor,
        new java.lang.String[] { "Id", "UserName", "LockCount", "FilePath", });
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoRequest_descriptor,
        new java.lang.String[] { "Category", "EventLogsData", });
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoFooter_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoFooter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_SystemInfoFooter_descriptor,
        new java.lang.String[] { "Category", });
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfo_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_info_malenkov_aspiahwinfo_proto_SystemInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiahwinfo_proto_SystemInfo_descriptor,
        new java.lang.String[] { "ComputerNet", "OperatingSystem", "Motherboard", "Bios", "Processor", "Memory", "LogicalDrives", "Printers", "NetworkAdapters", "NetworkShares", "WindowsDevices", "VideoAdapters", "Monitors", "PowerOptions", "Drivers", "Services", "EnvVars", "EventLogs", "Routes", "Connections", "Licenses", "Applications", "OpenFiles", "Footer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
