// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.key_exchange.proto

package info.malenkov.aspiahwinfo.proto;

public interface ClientHelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.ClientHello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 encryption = 1;</code>
   * @return The encryption.
   */
  int getEncryption();

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Identify identify = 2;</code>
   * @return The enum numeric value on the wire for identify.
   */
  int getIdentifyValue();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.Identify identify = 2;</code>
   * @return The identify.
   */
  info.malenkov.aspiahwinfo.proto.Identify getIdentify();

  /**
   * <code>bytes public_key = 3;</code>
   * @return The publicKey.
   */
  com.google.protobuf.ByteString getPublicKey();

  /**
   * <code>bytes iv = 4;</code>
   * @return The iv.
   */
  com.google.protobuf.ByteString getIv();
}
