// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiahwinfo.proto;

/**
 * Protobuf type {@code info.malenkov.aspiahwinfo.proto.DesktopConfigRequest}
 */
public final class DesktopConfigRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.DesktopConfigRequest)
    DesktopConfigRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DesktopConfigRequest.newBuilder() to construct.
  private DesktopConfigRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DesktopConfigRequest() {
    extensions_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DesktopConfigRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DesktopConfigRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            extensions_ = s;
            break;
          }
          case 16: {

            videoEncodings_ = input.readUInt32();
            break;
          }
          case 24: {

            audioEncodings_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiahwinfo.proto.AspiaDesktop.internal_static_info_malenkov_aspiahwinfo_proto_DesktopConfigRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiahwinfo.proto.AspiaDesktop.internal_static_info_malenkov_aspiahwinfo_proto_DesktopConfigRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiahwinfo.proto.DesktopConfigRequest.class, info.malenkov.aspiahwinfo.proto.DesktopConfigRequest.Builder.class);
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 1;
  private volatile java.lang.Object extensions_;
  /**
   * <code>string extensions = 1;</code>
   * @return The extensions.
   */
  @java.lang.Override
  public java.lang.String getExtensions() {
    java.lang.Object ref = extensions_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extensions_ = s;
      return s;
    }
  }
  /**
   * <code>string extensions = 1;</code>
   * @return The bytes for extensions.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtensionsBytes() {
    java.lang.Object ref = extensions_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extensions_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VIDEO_ENCODINGS_FIELD_NUMBER = 2;
  private int videoEncodings_;
  /**
   * <code>uint32 video_encodings = 2;</code>
   * @return The videoEncodings.
   */
  @java.lang.Override
  public int getVideoEncodings() {
    return videoEncodings_;
  }

  public static final int AUDIO_ENCODINGS_FIELD_NUMBER = 3;
  private int audioEncodings_;
  /**
   * <code>uint32 audio_encodings = 3;</code>
   * @return The audioEncodings.
   */
  @java.lang.Override
  public int getAudioEncodings() {
    return audioEncodings_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extensions_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, extensions_);
    }
    if (videoEncodings_ != 0) {
      output.writeUInt32(2, videoEncodings_);
    }
    if (audioEncodings_ != 0) {
      output.writeUInt32(3, audioEncodings_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extensions_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, extensions_);
    }
    if (videoEncodings_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, videoEncodings_);
    }
    if (audioEncodings_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, audioEncodings_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiahwinfo.proto.DesktopConfigRequest)) {
      return super.equals(obj);
    }
    info.malenkov.aspiahwinfo.proto.DesktopConfigRequest other = (info.malenkov.aspiahwinfo.proto.DesktopConfigRequest) obj;

    if (!getExtensions()
        .equals(other.getExtensions())) return false;
    if (getVideoEncodings()
        != other.getVideoEncodings()) return false;
    if (getAudioEncodings()
        != other.getAudioEncodings()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
    hash = (53 * hash) + getExtensions().hashCode();
    hash = (37 * hash) + VIDEO_ENCODINGS_FIELD_NUMBER;
    hash = (53 * hash) + getVideoEncodings();
    hash = (37 * hash) + AUDIO_ENCODINGS_FIELD_NUMBER;
    hash = (53 * hash) + getAudioEncodings();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.DesktopConfigRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.DesktopConfigRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.DesktopConfigRequest)
      info.malenkov.aspiahwinfo.proto.DesktopConfigRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaDesktop.internal_static_info_malenkov_aspiahwinfo_proto_DesktopConfigRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaDesktop.internal_static_info_malenkov_aspiahwinfo_proto_DesktopConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.DesktopConfigRequest.class, info.malenkov.aspiahwinfo.proto.DesktopConfigRequest.Builder.class);
    }

    // Construct using info.malenkov.aspiahwinfo.proto.DesktopConfigRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      extensions_ = "";

      videoEncodings_ = 0;

      audioEncodings_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiahwinfo.proto.AspiaDesktop.internal_static_info_malenkov_aspiahwinfo_proto_DesktopConfigRequest_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.DesktopConfigRequest getDefaultInstanceForType() {
      return info.malenkov.aspiahwinfo.proto.DesktopConfigRequest.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.DesktopConfigRequest build() {
      info.malenkov.aspiahwinfo.proto.DesktopConfigRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.DesktopConfigRequest buildPartial() {
      info.malenkov.aspiahwinfo.proto.DesktopConfigRequest result = new info.malenkov.aspiahwinfo.proto.DesktopConfigRequest(this);
      result.extensions_ = extensions_;
      result.videoEncodings_ = videoEncodings_;
      result.audioEncodings_ = audioEncodings_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiahwinfo.proto.DesktopConfigRequest) {
        return mergeFrom((info.malenkov.aspiahwinfo.proto.DesktopConfigRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.DesktopConfigRequest other) {
      if (other == info.malenkov.aspiahwinfo.proto.DesktopConfigRequest.getDefaultInstance()) return this;
      if (!other.getExtensions().isEmpty()) {
        extensions_ = other.extensions_;
        onChanged();
      }
      if (other.getVideoEncodings() != 0) {
        setVideoEncodings(other.getVideoEncodings());
      }
      if (other.getAudioEncodings() != 0) {
        setAudioEncodings(other.getAudioEncodings());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiahwinfo.proto.DesktopConfigRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiahwinfo.proto.DesktopConfigRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object extensions_ = "";
    /**
     * <code>string extensions = 1;</code>
     * @return The extensions.
     */
    public java.lang.String getExtensions() {
      java.lang.Object ref = extensions_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extensions_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extensions = 1;</code>
     * @return The bytes for extensions.
     */
    public com.google.protobuf.ByteString
        getExtensionsBytes() {
      java.lang.Object ref = extensions_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extensions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extensions = 1;</code>
     * @param value The extensions to set.
     * @return This builder for chaining.
     */
    public Builder setExtensions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extensions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extensions = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtensions() {
      
      extensions_ = getDefaultInstance().getExtensions();
      onChanged();
      return this;
    }
    /**
     * <code>string extensions = 1;</code>
     * @param value The bytes for extensions to set.
     * @return This builder for chaining.
     */
    public Builder setExtensionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extensions_ = value;
      onChanged();
      return this;
    }

    private int videoEncodings_ ;
    /**
     * <code>uint32 video_encodings = 2;</code>
     * @return The videoEncodings.
     */
    @java.lang.Override
    public int getVideoEncodings() {
      return videoEncodings_;
    }
    /**
     * <code>uint32 video_encodings = 2;</code>
     * @param value The videoEncodings to set.
     * @return This builder for chaining.
     */
    public Builder setVideoEncodings(int value) {
      
      videoEncodings_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 video_encodings = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoEncodings() {
      
      videoEncodings_ = 0;
      onChanged();
      return this;
    }

    private int audioEncodings_ ;
    /**
     * <code>uint32 audio_encodings = 3;</code>
     * @return The audioEncodings.
     */
    @java.lang.Override
    public int getAudioEncodings() {
      return audioEncodings_;
    }
    /**
     * <code>uint32 audio_encodings = 3;</code>
     * @param value The audioEncodings to set.
     * @return This builder for chaining.
     */
    public Builder setAudioEncodings(int value) {
      
      audioEncodings_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 audio_encodings = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioEncodings() {
      
      audioEncodings_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.DesktopConfigRequest)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.DesktopConfigRequest)
  private static final info.malenkov.aspiahwinfo.proto.DesktopConfigRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.DesktopConfigRequest();
  }

  public static info.malenkov.aspiahwinfo.proto.DesktopConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DesktopConfigRequest>
      PARSER = new com.google.protobuf.AbstractParser<DesktopConfigRequest>() {
    @java.lang.Override
    public DesktopConfigRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DesktopConfigRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DesktopConfigRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DesktopConfigRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.DesktopConfigRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

