// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface EventLogsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.EventLogs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogs.Event.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogs.Event.Type type = 1;</code>
   * @return The type.
   */
  info.malenkov.aspiahwinfo.proto.EventLogs.Event.Type getType();

  /**
   * <code>uint32 total_records = 2;</code>
   * @return The totalRecords.
   */
  int getTotalRecords();

  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.EventLogs.Event event = 3;</code>
   */
  java.util.List<info.malenkov.aspiahwinfo.proto.EventLogs.Event> 
      getEventList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.EventLogs.Event event = 3;</code>
   */
  info.malenkov.aspiahwinfo.proto.EventLogs.Event getEvent(int index);
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.EventLogs.Event event = 3;</code>
   */
  int getEventCount();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.EventLogs.Event event = 3;</code>
   */
  java.util.List<? extends info.malenkov.aspiahwinfo.proto.EventLogs.EventOrBuilder> 
      getEventOrBuilderList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.EventLogs.Event event = 3;</code>
   */
  info.malenkov.aspiahwinfo.proto.EventLogs.EventOrBuilder getEventOrBuilder(
      int index);
}
