// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

/**
 * Protobuf type {@code info.malenkov.aspiahwinfo.proto.LogicalDrives}
 */
public final class LogicalDrives extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.LogicalDrives)
    LogicalDrivesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogicalDrives.newBuilder() to construct.
  private LogicalDrives(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogicalDrives() {
    drive_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LogicalDrives();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LogicalDrives(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              drive_ = new java.util.ArrayList<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive>();
              mutable_bitField0_ |= 0x00000001;
            }
            drive_.add(
                input.readMessage(info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        drive_ = java.util.Collections.unmodifiableList(drive_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiahwinfo.proto.LogicalDrives.class, info.malenkov.aspiahwinfo.proto.LogicalDrives.Builder.class);
  }

  public interface DriveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>string file_system = 2;</code>
     * @return The fileSystem.
     */
    java.lang.String getFileSystem();
    /**
     * <code>string file_system = 2;</code>
     * @return The bytes for fileSystem.
     */
    com.google.protobuf.ByteString
        getFileSystemBytes();

    /**
     * <code>uint64 total_size = 3;</code>
     * @return The totalSize.
     */
    long getTotalSize();

    /**
     * <code>uint64 free_size = 4;</code>
     * @return The freeSize.
     */
    long getFreeSize();
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive}
   */
  public static final class Drive extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive)
      DriveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Drive.newBuilder() to construct.
    private Drive(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Drive() {
      path_ = "";
      fileSystem_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Drive();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Drive(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fileSystem_ = s;
              break;
            }
            case 24: {

              totalSize_ = input.readUInt64();
              break;
            }
            case 32: {

              freeSize_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.class, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder.class);
    }

    public static final int PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object path_;
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_SYSTEM_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileSystem_;
    /**
     * <code>string file_system = 2;</code>
     * @return The fileSystem.
     */
    @java.lang.Override
    public java.lang.String getFileSystem() {
      java.lang.Object ref = fileSystem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileSystem_ = s;
        return s;
      }
    }
    /**
     * <code>string file_system = 2;</code>
     * @return The bytes for fileSystem.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileSystemBytes() {
      java.lang.Object ref = fileSystem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_SIZE_FIELD_NUMBER = 3;
    private long totalSize_;
    /**
     * <code>uint64 total_size = 3;</code>
     * @return The totalSize.
     */
    @java.lang.Override
    public long getTotalSize() {
      return totalSize_;
    }

    public static final int FREE_SIZE_FIELD_NUMBER = 4;
    private long freeSize_;
    /**
     * <code>uint64 free_size = 4;</code>
     * @return The freeSize.
     */
    @java.lang.Override
    public long getFreeSize() {
      return freeSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileSystem_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileSystem_);
      }
      if (totalSize_ != 0L) {
        output.writeUInt64(3, totalSize_);
      }
      if (freeSize_ != 0L) {
        output.writeUInt64(4, freeSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileSystem_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileSystem_);
      }
      if (totalSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, totalSize_);
      }
      if (freeSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, freeSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive)) {
        return super.equals(obj);
      }
      info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive other = (info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive) obj;

      if (!getPath()
          .equals(other.getPath())) return false;
      if (!getFileSystem()
          .equals(other.getFileSystem())) return false;
      if (getTotalSize()
          != other.getTotalSize()) return false;
      if (getFreeSize()
          != other.getFreeSize()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + FILE_SYSTEM_FIELD_NUMBER;
      hash = (53 * hash) + getFileSystem().hashCode();
      hash = (37 * hash) + TOTAL_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalSize());
      hash = (37 * hash) + FREE_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFreeSize());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive)
        info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.class, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder.class);
      }

      // Construct using info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        path_ = "";

        fileSystem_ = "";

        totalSize_ = 0L;

        freeSize_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_Drive_descriptor;
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive getDefaultInstanceForType() {
        return info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.getDefaultInstance();
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive build() {
        info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive buildPartial() {
        info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive result = new info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive(this);
        result.path_ = path_;
        result.fileSystem_ = fileSystem_;
        result.totalSize_ = totalSize_;
        result.freeSize_ = freeSize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive) {
          return mergeFrom((info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive other) {
        if (other == info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.getDefaultInstance()) return this;
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (!other.getFileSystem().isEmpty()) {
          fileSystem_ = other.fileSystem_;
          onChanged();
        }
        if (other.getTotalSize() != 0L) {
          setTotalSize(other.getTotalSize());
        }
        if (other.getFreeSize() != 0L) {
          setFreeSize(other.getFreeSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileSystem_ = "";
      /**
       * <code>string file_system = 2;</code>
       * @return The fileSystem.
       */
      public java.lang.String getFileSystem() {
        java.lang.Object ref = fileSystem_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileSystem_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string file_system = 2;</code>
       * @return The bytes for fileSystem.
       */
      public com.google.protobuf.ByteString
          getFileSystemBytes() {
        java.lang.Object ref = fileSystem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileSystem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_system = 2;</code>
       * @param value The fileSystem to set.
       * @return This builder for chaining.
       */
      public Builder setFileSystem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileSystem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_system = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSystem() {
        
        fileSystem_ = getDefaultInstance().getFileSystem();
        onChanged();
        return this;
      }
      /**
       * <code>string file_system = 2;</code>
       * @param value The bytes for fileSystem to set.
       * @return This builder for chaining.
       */
      public Builder setFileSystemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileSystem_ = value;
        onChanged();
        return this;
      }

      private long totalSize_ ;
      /**
       * <code>uint64 total_size = 3;</code>
       * @return The totalSize.
       */
      @java.lang.Override
      public long getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>uint64 total_size = 3;</code>
       * @param value The totalSize to set.
       * @return This builder for chaining.
       */
      public Builder setTotalSize(long value) {
        
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 total_size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalSize() {
        
        totalSize_ = 0L;
        onChanged();
        return this;
      }

      private long freeSize_ ;
      /**
       * <code>uint64 free_size = 4;</code>
       * @return The freeSize.
       */
      @java.lang.Override
      public long getFreeSize() {
        return freeSize_;
      }
      /**
       * <code>uint64 free_size = 4;</code>
       * @param value The freeSize to set.
       * @return This builder for chaining.
       */
      public Builder setFreeSize(long value) {
        
        freeSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 free_size = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFreeSize() {
        
        freeSize_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive)
    }

    // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive)
    private static final info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive();
    }

    public static info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Drive>
        PARSER = new com.google.protobuf.AbstractParser<Drive>() {
      @java.lang.Override
      public Drive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Drive(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Drive> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Drive> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DRIVE_FIELD_NUMBER = 1;
  private java.util.List<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive> drive_;
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  @java.lang.Override
  public java.util.List<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive> getDriveList() {
    return drive_;
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder> 
      getDriveOrBuilderList() {
    return drive_;
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  @java.lang.Override
  public int getDriveCount() {
    return drive_.size();
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive getDrive(int index) {
    return drive_.get(index);
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder getDriveOrBuilder(
      int index) {
    return drive_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < drive_.size(); i++) {
      output.writeMessage(1, drive_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < drive_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, drive_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiahwinfo.proto.LogicalDrives)) {
      return super.equals(obj);
    }
    info.malenkov.aspiahwinfo.proto.LogicalDrives other = (info.malenkov.aspiahwinfo.proto.LogicalDrives) obj;

    if (!getDriveList()
        .equals(other.getDriveList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDriveCount() > 0) {
      hash = (37 * hash) + DRIVE_FIELD_NUMBER;
      hash = (53 * hash) + getDriveList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.LogicalDrives parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.LogicalDrives prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.LogicalDrives}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.LogicalDrives)
      info.malenkov.aspiahwinfo.proto.LogicalDrivesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.LogicalDrives.class, info.malenkov.aspiahwinfo.proto.LogicalDrives.Builder.class);
    }

    // Construct using info.malenkov.aspiahwinfo.proto.LogicalDrives.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDriveFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (driveBuilder_ == null) {
        drive_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        driveBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_LogicalDrives_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.LogicalDrives getDefaultInstanceForType() {
      return info.malenkov.aspiahwinfo.proto.LogicalDrives.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.LogicalDrives build() {
      info.malenkov.aspiahwinfo.proto.LogicalDrives result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.LogicalDrives buildPartial() {
      info.malenkov.aspiahwinfo.proto.LogicalDrives result = new info.malenkov.aspiahwinfo.proto.LogicalDrives(this);
      int from_bitField0_ = bitField0_;
      if (driveBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          drive_ = java.util.Collections.unmodifiableList(drive_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.drive_ = drive_;
      } else {
        result.drive_ = driveBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiahwinfo.proto.LogicalDrives) {
        return mergeFrom((info.malenkov.aspiahwinfo.proto.LogicalDrives)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.LogicalDrives other) {
      if (other == info.malenkov.aspiahwinfo.proto.LogicalDrives.getDefaultInstance()) return this;
      if (driveBuilder_ == null) {
        if (!other.drive_.isEmpty()) {
          if (drive_.isEmpty()) {
            drive_ = other.drive_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDriveIsMutable();
            drive_.addAll(other.drive_);
          }
          onChanged();
        }
      } else {
        if (!other.drive_.isEmpty()) {
          if (driveBuilder_.isEmpty()) {
            driveBuilder_.dispose();
            driveBuilder_ = null;
            drive_ = other.drive_;
            bitField0_ = (bitField0_ & ~0x00000001);
            driveBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDriveFieldBuilder() : null;
          } else {
            driveBuilder_.addAllMessages(other.drive_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiahwinfo.proto.LogicalDrives parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiahwinfo.proto.LogicalDrives) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive> drive_ =
      java.util.Collections.emptyList();
    private void ensureDriveIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        drive_ = new java.util.ArrayList<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive>(drive_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder, info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder> driveBuilder_;

    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public java.util.List<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive> getDriveList() {
      if (driveBuilder_ == null) {
        return java.util.Collections.unmodifiableList(drive_);
      } else {
        return driveBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public int getDriveCount() {
      if (driveBuilder_ == null) {
        return drive_.size();
      } else {
        return driveBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive getDrive(int index) {
      if (driveBuilder_ == null) {
        return drive_.get(index);
      } else {
        return driveBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder setDrive(
        int index, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive value) {
      if (driveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDriveIsMutable();
        drive_.set(index, value);
        onChanged();
      } else {
        driveBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder setDrive(
        int index, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder builderForValue) {
      if (driveBuilder_ == null) {
        ensureDriveIsMutable();
        drive_.set(index, builderForValue.build());
        onChanged();
      } else {
        driveBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder addDrive(info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive value) {
      if (driveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDriveIsMutable();
        drive_.add(value);
        onChanged();
      } else {
        driveBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder addDrive(
        int index, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive value) {
      if (driveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDriveIsMutable();
        drive_.add(index, value);
        onChanged();
      } else {
        driveBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder addDrive(
        info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder builderForValue) {
      if (driveBuilder_ == null) {
        ensureDriveIsMutable();
        drive_.add(builderForValue.build());
        onChanged();
      } else {
        driveBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder addDrive(
        int index, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder builderForValue) {
      if (driveBuilder_ == null) {
        ensureDriveIsMutable();
        drive_.add(index, builderForValue.build());
        onChanged();
      } else {
        driveBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder addAllDrive(
        java.lang.Iterable<? extends info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive> values) {
      if (driveBuilder_ == null) {
        ensureDriveIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, drive_);
        onChanged();
      } else {
        driveBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder clearDrive() {
      if (driveBuilder_ == null) {
        drive_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        driveBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public Builder removeDrive(int index) {
      if (driveBuilder_ == null) {
        ensureDriveIsMutable();
        drive_.remove(index);
        onChanged();
      } else {
        driveBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder getDriveBuilder(
        int index) {
      return getDriveFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder getDriveOrBuilder(
        int index) {
      if (driveBuilder_ == null) {
        return drive_.get(index);  } else {
        return driveBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public java.util.List<? extends info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder> 
         getDriveOrBuilderList() {
      if (driveBuilder_ != null) {
        return driveBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(drive_);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder addDriveBuilder() {
      return getDriveFieldBuilder().addBuilder(
          info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder addDriveBuilder(
        int index) {
      return getDriveFieldBuilder().addBuilder(
          index, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive drive = 1;</code>
     */
    public java.util.List<info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder> 
         getDriveBuilderList() {
      return getDriveFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder, info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder> 
        getDriveFieldBuilder() {
      if (driveBuilder_ == null) {
        driveBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive, info.malenkov.aspiahwinfo.proto.LogicalDrives.Drive.Builder, info.malenkov.aspiahwinfo.proto.LogicalDrives.DriveOrBuilder>(
                drive_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        drive_ = null;
      }
      return driveBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.LogicalDrives)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.LogicalDrives)
  private static final info.malenkov.aspiahwinfo.proto.LogicalDrives DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.LogicalDrives();
  }

  public static info.malenkov.aspiahwinfo.proto.LogicalDrives getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogicalDrives>
      PARSER = new com.google.protobuf.AbstractParser<LogicalDrives>() {
    @java.lang.Override
    public LogicalDrives parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LogicalDrives(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LogicalDrives> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogicalDrives> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.LogicalDrives getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

