// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

/**
 * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Printers}
 */
public final class Printers extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.Printers)
    PrintersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Printers.newBuilder() to construct.
  private Printers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Printers() {
    printer_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Printers();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Printers(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              printer_ = new java.util.ArrayList<info.malenkov.aspiahwinfo.proto.Printers.Printer>();
              mutable_bitField0_ |= 0x00000001;
            }
            printer_.add(
                input.readMessage(info.malenkov.aspiahwinfo.proto.Printers.Printer.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        printer_ = java.util.Collections.unmodifiableList(printer_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiahwinfo.proto.Printers.class, info.malenkov.aspiahwinfo.proto.Printers.Builder.class);
  }

  public interface PrinterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.Printers.Printer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bool default = 2;</code>
     * @return The default.
     */
    boolean getDefault();

    /**
     * <code>bool shared = 3;</code>
     * @return The shared.
     */
    boolean getShared();

    /**
     * <code>string port = 4;</code>
     * @return The port.
     */
    java.lang.String getPort();
    /**
     * <code>string port = 4;</code>
     * @return The bytes for port.
     */
    com.google.protobuf.ByteString
        getPortBytes();

    /**
     * <code>string driver = 5;</code>
     * @return The driver.
     */
    java.lang.String getDriver();
    /**
     * <code>string driver = 5;</code>
     * @return The bytes for driver.
     */
    com.google.protobuf.ByteString
        getDriverBytes();

    /**
     * <code>uint32 jobs_count = 6;</code>
     * @return The jobsCount.
     */
    int getJobsCount();

    /**
     * <code>string share_name = 7;</code>
     * @return The shareName.
     */
    java.lang.String getShareName();
    /**
     * <code>string share_name = 7;</code>
     * @return The bytes for shareName.
     */
    com.google.protobuf.ByteString
        getShareNameBytes();
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Printers.Printer}
   */
  public static final class Printer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:info.malenkov.aspiahwinfo.proto.Printers.Printer)
      PrinterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Printer.newBuilder() to construct.
    private Printer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Printer() {
      name_ = "";
      port_ = "";
      driver_ = "";
      shareName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Printer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Printer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              default_ = input.readBool();
              break;
            }
            case 24: {

              shared_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              port_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              driver_ = s;
              break;
            }
            case 48: {

              jobsCount_ = input.readUInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              shareName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.Printers.Printer.class, info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEFAULT_FIELD_NUMBER = 2;
    private boolean default_;
    /**
     * <code>bool default = 2;</code>
     * @return The default.
     */
    @java.lang.Override
    public boolean getDefault() {
      return default_;
    }

    public static final int SHARED_FIELD_NUMBER = 3;
    private boolean shared_;
    /**
     * <code>bool shared = 3;</code>
     * @return The shared.
     */
    @java.lang.Override
    public boolean getShared() {
      return shared_;
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private volatile java.lang.Object port_;
    /**
     * <code>string port = 4;</code>
     * @return The port.
     */
    @java.lang.Override
    public java.lang.String getPort() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        port_ = s;
        return s;
      }
    }
    /**
     * <code>string port = 4;</code>
     * @return The bytes for port.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPortBytes() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        port_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DRIVER_FIELD_NUMBER = 5;
    private volatile java.lang.Object driver_;
    /**
     * <code>string driver = 5;</code>
     * @return The driver.
     */
    @java.lang.Override
    public java.lang.String getDriver() {
      java.lang.Object ref = driver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        driver_ = s;
        return s;
      }
    }
    /**
     * <code>string driver = 5;</code>
     * @return The bytes for driver.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDriverBytes() {
      java.lang.Object ref = driver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        driver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBS_COUNT_FIELD_NUMBER = 6;
    private int jobsCount_;
    /**
     * <code>uint32 jobs_count = 6;</code>
     * @return The jobsCount.
     */
    @java.lang.Override
    public int getJobsCount() {
      return jobsCount_;
    }

    public static final int SHARE_NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object shareName_;
    /**
     * <code>string share_name = 7;</code>
     * @return The shareName.
     */
    @java.lang.Override
    public java.lang.String getShareName() {
      java.lang.Object ref = shareName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shareName_ = s;
        return s;
      }
    }
    /**
     * <code>string share_name = 7;</code>
     * @return The bytes for shareName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getShareNameBytes() {
      java.lang.Object ref = shareName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shareName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (default_ != false) {
        output.writeBool(2, default_);
      }
      if (shared_ != false) {
        output.writeBool(3, shared_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, port_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(driver_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, driver_);
      }
      if (jobsCount_ != 0) {
        output.writeUInt32(6, jobsCount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shareName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, shareName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (default_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, default_);
      }
      if (shared_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, shared_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, port_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(driver_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, driver_);
      }
      if (jobsCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, jobsCount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shareName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, shareName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof info.malenkov.aspiahwinfo.proto.Printers.Printer)) {
        return super.equals(obj);
      }
      info.malenkov.aspiahwinfo.proto.Printers.Printer other = (info.malenkov.aspiahwinfo.proto.Printers.Printer) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getDefault()
          != other.getDefault()) return false;
      if (getShared()
          != other.getShared()) return false;
      if (!getPort()
          .equals(other.getPort())) return false;
      if (!getDriver()
          .equals(other.getDriver())) return false;
      if (getJobsCount()
          != other.getJobsCount()) return false;
      if (!getShareName()
          .equals(other.getShareName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DEFAULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDefault());
      hash = (37 * hash) + SHARED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getShared());
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort().hashCode();
      hash = (37 * hash) + DRIVER_FIELD_NUMBER;
      hash = (53 * hash) + getDriver().hashCode();
      hash = (37 * hash) + JOBS_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getJobsCount();
      hash = (37 * hash) + SHARE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getShareName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.malenkov.aspiahwinfo.proto.Printers.Printer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.Printers.Printer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Printers.Printer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.Printers.Printer)
        info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.malenkov.aspiahwinfo.proto.Printers.Printer.class, info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder.class);
      }

      // Construct using info.malenkov.aspiahwinfo.proto.Printers.Printer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        default_ = false;

        shared_ = false;

        port_ = "";

        driver_ = "";

        jobsCount_ = 0;

        shareName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_Printer_descriptor;
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.Printers.Printer getDefaultInstanceForType() {
        return info.malenkov.aspiahwinfo.proto.Printers.Printer.getDefaultInstance();
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.Printers.Printer build() {
        info.malenkov.aspiahwinfo.proto.Printers.Printer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public info.malenkov.aspiahwinfo.proto.Printers.Printer buildPartial() {
        info.malenkov.aspiahwinfo.proto.Printers.Printer result = new info.malenkov.aspiahwinfo.proto.Printers.Printer(this);
        result.name_ = name_;
        result.default_ = default_;
        result.shared_ = shared_;
        result.port_ = port_;
        result.driver_ = driver_;
        result.jobsCount_ = jobsCount_;
        result.shareName_ = shareName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.malenkov.aspiahwinfo.proto.Printers.Printer) {
          return mergeFrom((info.malenkov.aspiahwinfo.proto.Printers.Printer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.Printers.Printer other) {
        if (other == info.malenkov.aspiahwinfo.proto.Printers.Printer.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getDefault() != false) {
          setDefault(other.getDefault());
        }
        if (other.getShared() != false) {
          setShared(other.getShared());
        }
        if (!other.getPort().isEmpty()) {
          port_ = other.port_;
          onChanged();
        }
        if (!other.getDriver().isEmpty()) {
          driver_ = other.driver_;
          onChanged();
        }
        if (other.getJobsCount() != 0) {
          setJobsCount(other.getJobsCount());
        }
        if (!other.getShareName().isEmpty()) {
          shareName_ = other.shareName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.malenkov.aspiahwinfo.proto.Printers.Printer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.malenkov.aspiahwinfo.proto.Printers.Printer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private boolean default_ ;
      /**
       * <code>bool default = 2;</code>
       * @return The default.
       */
      @java.lang.Override
      public boolean getDefault() {
        return default_;
      }
      /**
       * <code>bool default = 2;</code>
       * @param value The default to set.
       * @return This builder for chaining.
       */
      public Builder setDefault(boolean value) {
        
        default_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool default = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefault() {
        
        default_ = false;
        onChanged();
        return this;
      }

      private boolean shared_ ;
      /**
       * <code>bool shared = 3;</code>
       * @return The shared.
       */
      @java.lang.Override
      public boolean getShared() {
        return shared_;
      }
      /**
       * <code>bool shared = 3;</code>
       * @param value The shared to set.
       * @return This builder for chaining.
       */
      public Builder setShared(boolean value) {
        
        shared_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool shared = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearShared() {
        
        shared_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object port_ = "";
      /**
       * <code>string port = 4;</code>
       * @return The port.
       */
      public java.lang.String getPort() {
        java.lang.Object ref = port_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          port_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string port = 4;</code>
       * @return The bytes for port.
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        java.lang.Object ref = port_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string port = 4;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string port = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }
      /**
       * <code>string port = 4;</code>
       * @param value The bytes for port to set.
       * @return This builder for chaining.
       */
      public Builder setPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        port_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object driver_ = "";
      /**
       * <code>string driver = 5;</code>
       * @return The driver.
       */
      public java.lang.String getDriver() {
        java.lang.Object ref = driver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          driver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string driver = 5;</code>
       * @return The bytes for driver.
       */
      public com.google.protobuf.ByteString
          getDriverBytes() {
        java.lang.Object ref = driver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          driver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string driver = 5;</code>
       * @param value The driver to set.
       * @return This builder for chaining.
       */
      public Builder setDriver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        driver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string driver = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDriver() {
        
        driver_ = getDefaultInstance().getDriver();
        onChanged();
        return this;
      }
      /**
       * <code>string driver = 5;</code>
       * @param value The bytes for driver to set.
       * @return This builder for chaining.
       */
      public Builder setDriverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        driver_ = value;
        onChanged();
        return this;
      }

      private int jobsCount_ ;
      /**
       * <code>uint32 jobs_count = 6;</code>
       * @return The jobsCount.
       */
      @java.lang.Override
      public int getJobsCount() {
        return jobsCount_;
      }
      /**
       * <code>uint32 jobs_count = 6;</code>
       * @param value The jobsCount to set.
       * @return This builder for chaining.
       */
      public Builder setJobsCount(int value) {
        
        jobsCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 jobs_count = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobsCount() {
        
        jobsCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object shareName_ = "";
      /**
       * <code>string share_name = 7;</code>
       * @return The shareName.
       */
      public java.lang.String getShareName() {
        java.lang.Object ref = shareName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shareName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string share_name = 7;</code>
       * @return The bytes for shareName.
       */
      public com.google.protobuf.ByteString
          getShareNameBytes() {
        java.lang.Object ref = shareName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shareName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string share_name = 7;</code>
       * @param value The shareName to set.
       * @return This builder for chaining.
       */
      public Builder setShareName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shareName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string share_name = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearShareName() {
        
        shareName_ = getDefaultInstance().getShareName();
        onChanged();
        return this;
      }
      /**
       * <code>string share_name = 7;</code>
       * @param value The bytes for shareName to set.
       * @return This builder for chaining.
       */
      public Builder setShareNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shareName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.Printers.Printer)
    }

    // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.Printers.Printer)
    private static final info.malenkov.aspiahwinfo.proto.Printers.Printer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.Printers.Printer();
    }

    public static info.malenkov.aspiahwinfo.proto.Printers.Printer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Printer>
        PARSER = new com.google.protobuf.AbstractParser<Printer>() {
      @java.lang.Override
      public Printer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Printer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Printer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Printer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Printers.Printer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int PRINTER_FIELD_NUMBER = 1;
  private java.util.List<info.malenkov.aspiahwinfo.proto.Printers.Printer> printer_;
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
   */
  @java.lang.Override
  public java.util.List<info.malenkov.aspiahwinfo.proto.Printers.Printer> getPrinterList() {
    return printer_;
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder> 
      getPrinterOrBuilderList() {
    return printer_;
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
   */
  @java.lang.Override
  public int getPrinterCount() {
    return printer_.size();
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.Printers.Printer getPrinter(int index) {
    return printer_.get(index);
  }
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder getPrinterOrBuilder(
      int index) {
    return printer_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < printer_.size(); i++) {
      output.writeMessage(1, printer_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < printer_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, printer_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiahwinfo.proto.Printers)) {
      return super.equals(obj);
    }
    info.malenkov.aspiahwinfo.proto.Printers other = (info.malenkov.aspiahwinfo.proto.Printers) obj;

    if (!getPrinterList()
        .equals(other.getPrinterList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPrinterCount() > 0) {
      hash = (37 * hash) + PRINTER_FIELD_NUMBER;
      hash = (53 * hash) + getPrinterList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiahwinfo.proto.Printers parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiahwinfo.proto.Printers prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiahwinfo.proto.Printers}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiahwinfo.proto.Printers)
      info.malenkov.aspiahwinfo.proto.PrintersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiahwinfo.proto.Printers.class, info.malenkov.aspiahwinfo.proto.Printers.Builder.class);
    }

    // Construct using info.malenkov.aspiahwinfo.proto.Printers.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPrinterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (printerBuilder_ == null) {
        printer_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        printerBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiahwinfo.proto.AspiaSystemInfo.internal_static_info_malenkov_aspiahwinfo_proto_Printers_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Printers getDefaultInstanceForType() {
      return info.malenkov.aspiahwinfo.proto.Printers.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Printers build() {
      info.malenkov.aspiahwinfo.proto.Printers result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiahwinfo.proto.Printers buildPartial() {
      info.malenkov.aspiahwinfo.proto.Printers result = new info.malenkov.aspiahwinfo.proto.Printers(this);
      int from_bitField0_ = bitField0_;
      if (printerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          printer_ = java.util.Collections.unmodifiableList(printer_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.printer_ = printer_;
      } else {
        result.printer_ = printerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiahwinfo.proto.Printers) {
        return mergeFrom((info.malenkov.aspiahwinfo.proto.Printers)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiahwinfo.proto.Printers other) {
      if (other == info.malenkov.aspiahwinfo.proto.Printers.getDefaultInstance()) return this;
      if (printerBuilder_ == null) {
        if (!other.printer_.isEmpty()) {
          if (printer_.isEmpty()) {
            printer_ = other.printer_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePrinterIsMutable();
            printer_.addAll(other.printer_);
          }
          onChanged();
        }
      } else {
        if (!other.printer_.isEmpty()) {
          if (printerBuilder_.isEmpty()) {
            printerBuilder_.dispose();
            printerBuilder_ = null;
            printer_ = other.printer_;
            bitField0_ = (bitField0_ & ~0x00000001);
            printerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPrinterFieldBuilder() : null;
          } else {
            printerBuilder_.addAllMessages(other.printer_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiahwinfo.proto.Printers parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiahwinfo.proto.Printers) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<info.malenkov.aspiahwinfo.proto.Printers.Printer> printer_ =
      java.util.Collections.emptyList();
    private void ensurePrinterIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        printer_ = new java.util.ArrayList<info.malenkov.aspiahwinfo.proto.Printers.Printer>(printer_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiahwinfo.proto.Printers.Printer, info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder, info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder> printerBuilder_;

    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public java.util.List<info.malenkov.aspiahwinfo.proto.Printers.Printer> getPrinterList() {
      if (printerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(printer_);
      } else {
        return printerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public int getPrinterCount() {
      if (printerBuilder_ == null) {
        return printer_.size();
      } else {
        return printerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Printers.Printer getPrinter(int index) {
      if (printerBuilder_ == null) {
        return printer_.get(index);
      } else {
        return printerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder setPrinter(
        int index, info.malenkov.aspiahwinfo.proto.Printers.Printer value) {
      if (printerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePrinterIsMutable();
        printer_.set(index, value);
        onChanged();
      } else {
        printerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder setPrinter(
        int index, info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder builderForValue) {
      if (printerBuilder_ == null) {
        ensurePrinterIsMutable();
        printer_.set(index, builderForValue.build());
        onChanged();
      } else {
        printerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder addPrinter(info.malenkov.aspiahwinfo.proto.Printers.Printer value) {
      if (printerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePrinterIsMutable();
        printer_.add(value);
        onChanged();
      } else {
        printerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder addPrinter(
        int index, info.malenkov.aspiahwinfo.proto.Printers.Printer value) {
      if (printerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePrinterIsMutable();
        printer_.add(index, value);
        onChanged();
      } else {
        printerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder addPrinter(
        info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder builderForValue) {
      if (printerBuilder_ == null) {
        ensurePrinterIsMutable();
        printer_.add(builderForValue.build());
        onChanged();
      } else {
        printerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder addPrinter(
        int index, info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder builderForValue) {
      if (printerBuilder_ == null) {
        ensurePrinterIsMutable();
        printer_.add(index, builderForValue.build());
        onChanged();
      } else {
        printerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder addAllPrinter(
        java.lang.Iterable<? extends info.malenkov.aspiahwinfo.proto.Printers.Printer> values) {
      if (printerBuilder_ == null) {
        ensurePrinterIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, printer_);
        onChanged();
      } else {
        printerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder clearPrinter() {
      if (printerBuilder_ == null) {
        printer_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        printerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public Builder removePrinter(int index) {
      if (printerBuilder_ == null) {
        ensurePrinterIsMutable();
        printer_.remove(index);
        onChanged();
      } else {
        printerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder getPrinterBuilder(
        int index) {
      return getPrinterFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder getPrinterOrBuilder(
        int index) {
      if (printerBuilder_ == null) {
        return printer_.get(index);  } else {
        return printerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public java.util.List<? extends info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder> 
         getPrinterOrBuilderList() {
      if (printerBuilder_ != null) {
        return printerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(printer_);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder addPrinterBuilder() {
      return getPrinterFieldBuilder().addBuilder(
          info.malenkov.aspiahwinfo.proto.Printers.Printer.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder addPrinterBuilder(
        int index) {
      return getPrinterFieldBuilder().addBuilder(
          index, info.malenkov.aspiahwinfo.proto.Printers.Printer.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiahwinfo.proto.Printers.Printer printer = 1;</code>
     */
    public java.util.List<info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder> 
         getPrinterBuilderList() {
      return getPrinterFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiahwinfo.proto.Printers.Printer, info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder, info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder> 
        getPrinterFieldBuilder() {
      if (printerBuilder_ == null) {
        printerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            info.malenkov.aspiahwinfo.proto.Printers.Printer, info.malenkov.aspiahwinfo.proto.Printers.Printer.Builder, info.malenkov.aspiahwinfo.proto.Printers.PrinterOrBuilder>(
                printer_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        printer_ = null;
      }
      return printerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiahwinfo.proto.Printers)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiahwinfo.proto.Printers)
  private static final info.malenkov.aspiahwinfo.proto.Printers DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiahwinfo.proto.Printers();
  }

  public static info.malenkov.aspiahwinfo.proto.Printers getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Printers>
      PARSER = new com.google.protobuf.AbstractParser<Printers>() {
    @java.lang.Override
    public Printers parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Printers(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Printers> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Printers> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiahwinfo.proto.Printers getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

