// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface ProcessorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.Processor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vendor = 1;</code>
   * @return The vendor.
   */
  java.lang.String getVendor();
  /**
   * <code>string vendor = 1;</code>
   * @return The bytes for vendor.
   */
  com.google.protobuf.ByteString
      getVendorBytes();

  /**
   * <code>string model = 2;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>uint32 packages = 3;</code>
   * @return The packages.
   */
  int getPackages();

  /**
   * <code>uint32 cores = 4;</code>
   * @return The cores.
   */
  int getCores();

  /**
   * <code>uint32 threads = 5;</code>
   * @return The threads.
   */
  int getThreads();
}
