// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface RoutesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.Routes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Routes.Route route = 1;</code>
   */
  java.util.List<info.malenkov.aspiahwinfo.proto.Routes.Route> 
      getRouteList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Routes.Route route = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.Routes.Route getRoute(int index);
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Routes.Route route = 1;</code>
   */
  int getRouteCount();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Routes.Route route = 1;</code>
   */
  java.util.List<? extends info.malenkov.aspiahwinfo.proto.Routes.RouteOrBuilder> 
      getRouteOrBuilderList();
  /**
   * <code>repeated .info.malenkov.aspiahwinfo.proto.Routes.Route route = 1;</code>
   */
  info.malenkov.aspiahwinfo.proto.Routes.RouteOrBuilder getRouteOrBuilder(
      int index);
}
