// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.system_info.proto

package info.malenkov.aspiahwinfo.proto;

public interface SystemInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiahwinfo.proto.SystemInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string category = 1;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <pre>
   * Fields 2 - 10: Reserved.
   * </pre>
   *
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogsData event_logs_data = 11;</code>
   * @return Whether the eventLogsData field is set.
   */
  boolean hasEventLogsData();
  /**
   * <pre>
   * Fields 2 - 10: Reserved.
   * </pre>
   *
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogsData event_logs_data = 11;</code>
   * @return The eventLogsData.
   */
  info.malenkov.aspiahwinfo.proto.EventLogsData getEventLogsData();
  /**
   * <pre>
   * Fields 2 - 10: Reserved.
   * </pre>
   *
   * <code>.info.malenkov.aspiahwinfo.proto.EventLogsData event_logs_data = 11;</code>
   */
  info.malenkov.aspiahwinfo.proto.EventLogsDataOrBuilder getEventLogsDataOrBuilder();
}
